### ISSUE TITLE
Destroy Global Event Listener

### ISSUE THREAD

**Issue by indper** [OptimalBits/bull#1000]
## Error Description
Hi,
I have a function for waiting complete job by Job Id. But, unfortunately i got problem 
```
(node:19826) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 global:completed listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:280:19)
    at Queue.addListener (events.js:297:10)
    at Queue.on (/home/test/node_modules/bull/lib/queue.js:335:14)
    at /home/test/lib/helpers/queueHelper.js:28:19
    at new Promise (<anonymous>)
    at Object.module.exports.waitJob (/home/test/lib/helpers/queueHelper.js:26:9)
    at /home/test/api/test/index.js:20:79
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
I think the problem because i did't destroy event listener for every function request. Could you give an example how to destroy global event listener safely for Bull Queue?
Thank you.

## Code
```javascript
module.exports.waitJob = function (queueId){
      return new Promise(function(resolve, reject) {
        var jobId = queueId.jobId;
        testQueue.on('global:completed', function(jobId, result) {
            //console.log('Job ${jobId} completed! Result: ${result}');
            testQueue.getJob(jobId).then(function(job) {
                //console.log('Job Data Remove', job.data);
                if (job != null){
                    job.remove();
                    //console.log(`Remove Job ${jobId}`);
                    resolve(result);
                }
            });
        });
	});		
} 
```
## Bull version
3.4.2 NodeJS 8.11.1

**Comment by manast** [comment]
why not use ```once``` instead of ```on``` ?

**Comment by manast** [comment]
Maybe you can use the ```finished``` method: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#jobfinished
