### ISSUE TITLE
TypeError: queue.client.moveToActive is not a function

### ISSUE THREAD

**Issue by prash317** [OptimalBits/bull#1049]
Hi @manast,

I am a new user of bull, and have a requirement of implementing a pull based queue. Till now I've tried using [manually-fetching-jobs ](https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#manually-fetching-jobs) pattern given in the bull patterns doc, but getting error stating queue.client.moveToActive is not a function. 
Below is the way I'm trying to implement it:
```js
import redis from 'redis';
import Queue from 'bull';

async function getJobFromQueue() {
	console.log('Hello.....');
	let queue = new Queue('examReEvaluationQueue', 'redis://127.0.0.1:6379');
	let job = await queue.getNextJob();
	console.log('job... ', job);
}
```

The above function is in processor.js file which is in a different directory. The job is getting added in different file (in different dir), which is as below:

```js
import Queue from 'bull';

let addJobOpts = {
	removeOnComplete: true
};
let queue = new Queue('examReEvaluationQueue', 'redis://127.0.0.1:6379');
queue.add('jobName', data, addJobOpts);
```

But when I execute this code, the data is getting pushed in the queue (I verified it in redis), but queue.getNextJob fails with below error, and hence it doesn't show any job:

```bash
NODE_DEBUG=bull nodemon ./index.js 
[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./index.js`
Try to connect to MongoDB via Mongoose ...
Hello.....
(node:23746) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
Unhandled rejection TypeError: queue.client.moveToActive is not a function
    at Object.moveToActive (/home/prash/workspace/me-admin/node_modules/bull/lib/scripts.js:97:25)
    at Queue.moveToActive (/home/prash/workspace/me-admin/node_modules/bull/lib/queue.js:1083:18)
    at Queue.getNextJob (/home/prash/workspace/me-admin/node_modules/bull/lib/queue.js:1077:17)
    at _callee$ (/home/prash/workspace/me-admin/Processors/exam_reevaluator/examReEvaluator.js:302:24)
    at tryCatch (/home/prash/workspace/me-admin/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/prash/workspace/me-admin/node_modules/regenerator-runtime/runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/prash/workspace/me-admin/node_modules/regenerator-runtime/runtime.js:114:21)
    at GeneratorFunctionPrototype.tryCatcher (/home/prash/workspace/me-admin/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/prash/workspace/me-admin/node_modules/bluebird/js/release/generators.js:97:49)
    at /home/prash/workspace/me-admin/node_modules/bluebird/js/release/generators.js:201:15
    at getJobFromQueue (/home/prash/workspace/me-admin/Processors/exam_reevaluator/examReEvaluator.js:326:15)
    at Object.<anonymous> (/home/prash/workspace/me-admin/Processors/exam_reevaluator/examReEvaluator.js:310:1)
    at Module._compile (module.js:570:32)
    at loader (/home/prash/workspace/me-admin/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/prash/workspace/me-admin/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/prash/workspace/me-admin/Processors/exam_reevaluator/index.js:4:1)
    at Module._compile (module.js:570:32)

Connected to MongoDB !
BULL 23746: examReEvaluationQueue queue ready
```

when I tried logging queue.client in scripts.js, moveToActive function, it shows Redis as client but does not list moveToActive as a method. Its output is as below:
```js
Redis {
  options: 
   { port: 6379,
     host: '127.0.0.1',
     db: 0,
     retryStrategy: [Function: retryStrategy],
     family: 4,
     connectTimeout: 10000,
     keepAlive: 0,
     noDelay: true,
     connectionName: null,
     sentinels: null,
     name: null,
     role: 'master',
     sentinelRetryStrategy: [Function: sentinelRetryStrategy],
     password: null,
     dropBufferSupport: false,
     enableOfflineQueue: true,
     enableReadyCheck: true,
     autoResubscribe: true,
     autoResendUnfulfilledCommands: true,
     lazyConnect: false,
     keyPrefix: '',
     reconnectOnError: null,
     readOnly: false,
     stringNumbers: false,
     showFriendlyErrorStack: false },
  domain: null,
  _events: 
   { error: [ [Function: bound emit], [Object] ],
     ready: { [Function: g] listener: [Function: handleReady] } },
  _eventsCount: 2,
  _maxListeners: undefined,
  scriptsSet: {},
  commandQueue: Denque { _head: 0, _tail: 0, _capacityMask: 3, _list: [ , , ,  ] },
  offlineQueue: 
   Denque {
     _head: 0,
     _tail: 1,
     _capacityMask: 3,
     _list: [ [Object], , ,  ] },
  connector: 
   Connector {
     options: 
      { port: 6379,
        host: '127.0.0.1',
        db: 0,
        retryStrategy: [Function: retryStrategy],
        family: 4,
        connectTimeout: 10000,
        keepAlive: 0,
        noDelay: true,
        connectionName: null,
        sentinels: null,
        name: null,
        role: 'master',
        sentinelRetryStrategy: [Function: sentinelRetryStrategy],
        password: null,
        dropBufferSupport: false,
        enableOfflineQueue: true,
        enableReadyCheck: true,
        autoResubscribe: true,
        autoResendUnfulfilledCommands: true,
        lazyConnect: false,
        keyPrefix: '',
        reconnectOnError: null,
        readOnly: false,
        stringNumbers: false,
        showFriendlyErrorStack: false },
     connecting: true },
  retryAttempts: 0,
  status: 'connecting',
  condition: { select: 0, auth: null, subscriber: false } }
```

Can you please confirm, if this is the correct way to use it? Also, if I can't use getNextJob (in case it's a private function), then do we have a way to use bull queue with pull fashion.

OS: Ubuntu 18.04
Node version: v6.10.0
Bull version: bull@3.4.2
Redis version: 4.0.9

Any help regarding this issue will be highly appreciated.
Thanks

**Comment by manast** [comment]
try this: 
```js
async function getJobFromQueue() {
	console.log('Hello.....');
	const queue = new Queue('examReEvaluationQueue', 'redis://127.0.0.1:6379');
         await queue.isReady();
	const job = await queue.getNextJob();
	console.log('job... ', job);
}
```

**Comment by prash317** [comment]
Thanks for the prompt help @manast, it worked. :)
so as per your changes, it seems like, the queue initialization takes some time and hence we need to wait and check for its readiness using isReady() function. Kindly rectify me, if I'm no getting it right.

**Comment by manast** [comment]
in this particular case yes, we should have a wrapped version of ```getNextJob``` that calls ```isReady``` internally to avoid these kind of problems.

**Comment by manast** [comment]
can we close this?

**Comment by prash317** [comment]
Thanks for the explanation.
Closing it :)
