### ISSUE TITLE
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection: Error: connect ETIMEDOUT  

### ISSUE THREAD

**Issue by amitabhroy** [OptimalBits/bull#1123]
## Description
We are getting this exception on our project during server start up. Here is the stack trace for it
```
Error: connect ETIMEDOUT
    at Socket.<anonymous> (/home/ubuntu/securenyx360-api/node_modules/ioredis/lib/redis.js:289:21)
    at Object.onceWrapper (events.js:255:19)
    at Socket.emit (events.js:160:13)
    at Socket._onTimeout (net.js:412:8)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
From previous event:
    at Object.isRedisReady (/home/ubuntu/securenyx360-api/node_modules/bull/lib/utils.js:27:10)
    at /home/ubuntu/securenyx360-api/node_modules/bull/lib/commands/index.js:31:18
    at /home/ubuntu/securenyx360-api/node_modules/bull/lib/queue.js:147:29
    at Queue.<anonymous> (/home/ubuntu/securenyx360-api/node_modules/bull/lib/queue.js:279:14)
    at new Queue (/home/ubuntu/securenyx360-api/node_modules/bull/lib/queue.js:178:26)
    at /home/ubuntu/securenyx360-api/config/queue.js:30:15
    at /home/ubuntu/securenyx360-api/node_modules/lodash/lodash.js:3563:27
    at /home/ubuntu/securenyx360-api/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/ubuntu/securenyx360-api/node_modules/lodash/lodash.js:3010:24)
    at /home/ubuntu/securenyx360-api/node_modules/lodash/lodash.js:4894:18
    at baseMap (/home/ubuntu/securenyx360-api/node_modules/lodash/lodash.js:3562:7)
    at Function.map (/home/ubuntu/securenyx360-api/node_modules/lodash/lodash.js:9554:14)
    at Object.<anonymous> (/home/ubuntu/securenyx360-api/config/queue.js:29:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.queue (/home/ubuntu/securenyx360-api/config/index.js:10:31)
    at Object.<anonymous> (/home/ubuntu/securenyx360-api/api/helpers/QueueHelper.js:2:27)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /home/ubuntu/securenyx360-api/node_modules/require-all/index.js:52:46
    at Array.forEach (<anonymous>)
```

This is how we are initializing bull queue, i.e. contents of /home/ubuntu/securenyx360-api/config/queue.js
```
const _ = require('lodash');
const Constants     = require('./constants');
var Queue = require('bull');

var Bq = {};

let QueueOptions =  {
    settings: {
        lockDuration: 3000, // Key expiration time for job locks.
        stalledInterval: 0, // How often check for stalled jobs (use 0 for never checking).
        maxStalledCount: 1, // Max amount of times a stalled job will be re-processed.
        guardInterval: 500, // Poll interval for delayed jobs and added jobs.
        retryProcessDelay: 400, // delay before processing next job in case of internal error.
    },
};

_.map(Constants.PUSH_NOTIFICATIONS,function (key) {
    Bq[key] = new Queue(key, 'redis://127.0.0.1:6379',QueueOptions);
});

_.map(Constants.QUEUES,function (key) {
    Bq[key] = new Queue(key, 'redis://127.0.0.1:6379',QueueOptions);
});

module.exports =  Bq;
  
```

We are not sure why this issue is happening, do you see anything that we are doing wrong which might cause the issue? 
## Bull version
3.4.4

**Comment by manast** [comment]
I think the problem may be that the redis server is not yet ready when you instantiate the queue. For next versions we are going to improve the connectivity, but for now I think you should somehow implement a mechanism that waits for redis to be available before trying to connect to it.

**Comment by manast** [comment]
but I guess this does only happen in this particular context? if you just do:

```
const myQueue = new Queue('test');
```

works right?

in that case I would go step by step completing with the code above until you find what is breaking it.

**Comment by binarymee** [comment]
The same thing is happening for me as well. I am just instantiating the queue and redis is up and running. When I restart the application, I am getting the following error. 

```Unhandled rejection Error: connect ETIMEDOUT
    at Socket.<anonymous> (/Users/mac/app-v1/node_modules/ioredis/lib/redis.js:289:21)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Socket._onTimeout (net.js:449:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)```

bull => `3.3.10`
ioredis => `3.1.4`
redis => `2.6.3`
