### ISSUE TITLE
Inconsistent and unexpected queue processing 

### ISSUE THREAD

**Issue by cbarlow1993** [OptimalBits/bull#1142]
## Description
I've created an API to add new Jobs to the queue. However I am experiencing unexpected behaviour in my Queue process where it crashes when the inputs are exactly the same. My processes are separate files as basic as: 

```
module.exports = async (job) => {
  try {
    console.log('IN JOB PROCESSING');
    console.log(job.data);

    return Promise.resolve();
  } catch (err) {
    console.log(err);
    return Promise.reject(err);
  }
};

```

My queues are defined as (where variables of the queues come through the API):

```
queue.fn.process('*', `${__dirname}/processes/${queue.processName}`)
```

And added via the API through: 

```
await queueList.queueList[queue].fn.add(name, payload, {
      priority: priority || 5,
});
```

I've sent the exact API request 5 times to test, of which 3/5 crash with an error. See the logs below. The 3rd and 5th request return fine whilst 3 of the job processes fail with an error I can't suss out. 
```
  *** NEW REQUEST ***
 POST /v1/jobs?queue=SCRAPE_S3&name=test 201 16.213 ms - 2
 /app/node_modules/bull/lib/process/master.js:86
   throw err;
   ^

 TypeError: expecting a function but got [object Object]
     at Function.Promise.method (/app/node_modules/bluebird/js/release/method.js:9:15)
     at process.<anonymous> (/app/node_modules/bull/lib/process/master.js:38:29)
     at emitTwo (events.js:126:13)
     at process.emit (events.js:214:7)
     at emit (internal/child_process.js:762:12)
     at _combinedTickCallback (internal/process/next_tick.js:142:11)
     at process._tickCallback (internal/process/next_tick.js:181:9)

  *** NEW REQUEST ***
 POST /v1/jobs?queue=SCRAPE_S3&name=test 201 10.508 ms - 2
 /app/node_modules/bull/lib/process/master.js:86
   throw err;
   ^

 TypeError: expecting a function but got [object Object]
     at Function.Promise.method (/app/node_modules/bluebird/js/release/method.js:9:15)
     at process.<anonymous> (/app/node_modules/bull/lib/process/master.js:38:29)
     at emitTwo (events.js:126:13)
     at process.emit (events.js:214:7)
     at emit (internal/child_process.js:762:12)
     at _combinedTickCallback (internal/process/next_tick.js:142:11)
     at process._tickCallback (internal/process/next_tick.js:181:9)

  *** NEW REQUEST ***
 POST /v1/jobs?queue=SCRAPE_S3&name=test 201 1.957 ms - 2
 IN JOB PROCESSING
 {}

  *** NEW REQUEST ***
 POST /v1/jobs?queue=SCRAPE_S3&name=test 201 9.747 ms - 2
 /app/node_modules/bull/lib/process/master.js:86
   throw err;
   ^

 TypeError: expecting a function but got [object Object]
     at Function.Promise.method (/app/node_modules/bluebird/js/release/method.js:9:15)
     at process.<anonymous> (/app/node_modules/bull/lib/process/master.js:38:29)
     at emitTwo (events.js:126:13)
     at process.emit (events.js:214:7)
     at emit (internal/child_process.js:762:12)
     at _combinedTickCallback (internal/process/next_tick.js:142:11)
     at process._tickCallback (internal/process/next_tick.js:181:9)

  *** NEW REQUEST ***
 POST /v1/jobs?queue=SCRAPE_S3&name=test 201 8.483 ms - 2
 /app/node_modules/bull/lib/process/master.js:86
   throw err;
   ^

 TypeError: expecting a function but got [object Object]
     at Function.Promise.method (/app/node_modules/bluebird/js/release/method.js:9:15)
     at process.<anonymous> (/app/node_modules/bull/lib/process/master.js:38:29)
     at emitTwo (events.js:126:13)
     at process.emit (events.js:214:7)
     at emit (internal/child_process.js:762:12)
     at _combinedTickCallback (internal/process/next_tick.js:142:11)
     at process._tickCallback (internal/process/next_tick.js:181:9)

  *** NEW REQUEST ***
 IN JOB PROCESSING
 {}
 POST /v1/jobs?queue=SCRAPE_S3&name=test 201 4.944 ms - 2
```

## Bull version
    "bull": "^3.5.2"
## Additional information
NODE_VERSION 8.13.0

**Comment by manast** [comment]
Can you really reproduce the error with the processor function that you wrote above?
```module.exports = async (job) => {
  try {
    console.log('IN JOB PROCESSING');
    console.log(job.data);

    return Promise.resolve();
  } catch (err) {
    console.log(err);
    return Promise.reject(err);
  }
};```

**Comment by cbarlow1993** [comment]
That is basic as I have it in my code and the output is exactly as defined. I’ve stripped it down to the minimum as I’ve been scratching my head around it for the last 48 hours. I’m completely lost! 

If you don’t have any suggestions as to why it might happen, I’ll try publish the entirety of my code and hopefully you might reproduce.

**Comment by manast** [comment]
@cbarlow1993 you should start from the minimal code that works and then build upon it until the bug appears, that way you will nail it down.

**Comment by manast** [comment]
@cbarlow1993 did you find the cause for the issue?
