### ISSUE TITLE
Delay job even if the queue is empty

### ISSUE THREAD

**Issue by jesucarr** [OptimalBits/bull#115]
It seems that when the queue is empty the first job added gets executed immediately, even if the opts have a delay. I would like to add jobs to my queue that get executed at some point in the future, including the first one. Is there any way to do that?

**Comment by manast** [comment]
strange, that is not suppose to happen. A job should be delayed always independently how many jobs there are in the queue at the moment of inserting it. I will investigate.

**Comment by jesucarr** [comment]
ok I just realised that it was behaving like that because it seems that my queue got corrupted. Changing the name of the queue worked as expected. The error raised is:

    Possibly unhandled Error: ERR Error running script (call to f_4e935277f8e885ee453aa99cb75651edbb889e58): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value 

    at ReplyParser.<anonymous> (/Users/j/Dev/test/node_modules/bull/node_modules/redis/index.js:317:31)
        at ReplyParser.emit (events.js:107:17)
        at ReplyParser.send_error (/Users/j/Dev/test/node_modules/bull/node_modules/redis/lib/parser/javascript.js:296:10)
        at ReplyParser.execute (/Users/j/Dev/test/node_modules/bull/node_modules/redis/lib/parser/javascript.js:181:22)
        at RedisClient.on_data (/Users/j/Dev/test/node_modules/bull/node_modules/redis/index.js:547:27)
        at Socket.<anonymous> (/Users/j/Dev/test/node_modules/bull/node_modules/redis/index.js:102:14)
        at Socket.emit (events.js:107:17)
        at readableAddChunk (_stream_readable.js:163:16)
        at Socket.Readable.push (_stream_readable.js:126:10)
        at TCP.onread (net.js:529:20)

Calling `.empty()`, also fixed it.

Maybe I did something strange from my script because I'm testing different things, so I'm closing this issue. Or is there something I should do to prevent this kind of errors?
