### ISSUE TITLE
Connecting to AWS Elasticache Redis Cluster

### ISSUE THREAD

**Issue by TNieminen** [OptimalBits/bull#1158]
## Description

I'm trying to make Bull work with Elasticache Cluster, but I'm having quite a bad time with it.
I based my code on the "cluster" part of the documentation, but I just get the error written below. : / 

## The code

```javascript

const RedisOpts = {
  port: REDIS_PORT,
  host: REDIS_HOST,
  password: REDIS_PASSWORD
}

exports.initAudioQueue = () => {
  return new Promise((resolve, reject) => {
    const audioQueue = new Queue(
      'jobQueue', {
        prefix:'{jobQueueCluster}',
        redis: RedisOpts
      });
    audioQueue.resume().then(() => {
      resolve(audioQueue)
    })
  });
}
```

## The error

```
2018-12-17T14:02:20.853Z	5eea9fa6-0204-11e9-8f05-db7f04a8117f	(node:1) UnhandledPromiseRejectionWarning: ReplyError: MOVED 7746 172.31.7.22:6379
at JavascriptRedisParser.returnError (/var/task/node_modules/bull/node_modules/ioredis/lib/redis/parser.js:24:25)
at JavascriptRedisParser.execute (/var/task/node_modules/redis-parser/lib/parser.js:572:12)
at Socket.<anonymous> (/var/task/node_modules/bull/node_modules/ioredis/lib/redis/event_handler.js:107:22)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:607:20)
```

## Bull version
3.5.2
## Additional information
Redis version of AWS 5.0.0

**Comment by manast** [comment]
seems like some kind of misconfiguration of the cluster. Does it work if you use ioredis directly and perform some commands?
Also, I am not sure if Bull will work in cluster mode due to an issue in ioredis, too late for me to find it now...

**Comment by TNieminen** [comment]
Just noticed that this will not work on Redis engine 5.0 on Elasticache.
Downgraded to 4.0.10 to make it work.

## Samplecode

```javascript
const Queue = require('bull');
const Redis = require('ioredis')

exports.initAudioQueue = () => {
  return new Promise((resolve, reject) => {
    const audioQueue = new Queue(
          'cluster', {
            prefix: '{audiocluster}',
            createClient: (type, config) => new Redis.Cluster([{
              port: REDIS_PORT,
              host: REDIS_HOST
            }])
          })
    resolve(audioQueue)
  });
}
```

**Comment by wtfleming** [comment]
We saw a similar issue if we used a Redis that had been launched with "Cluster Mode enabled".

But Redis 5.0.0 worked for us on ElastiCache as long as we did not use clustered redis.
