### ISSUE TITLE
Warning: a promise was created in a handler: from remove event handler

### ISSUE THREAD

**Issue by JakubPetriska** [OptimalBits/bull#1175]
## Description
I'm getting following exception printed into console:
```
(node:3948) Warning: a promise was created in a handler at home/jakubp/Projects/guzzler/node_modules/bull/lib/job.js:411:15 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (/home/jakubp/Projects/guzzler/node_modules/bluebird/js/release/promise.js:79:10)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at new Pipeline (/home/jakubp/Projects/guzzler/node_modules/ioredis/lib/pipeline.js:30:18)
    at Redis.redis.multi (/home/jakubp/Projects/guzzler/node_modules/ioredis/lib/transaction.js:24:20)
    at Queue.multi (/home/jakubp/Projects/guzzler/node_modules/bull/lib/queue.js:1089:22)
    at Queue.getRanges (/home/jakubp/Projects/guzzler/node_modules/bull/lib/getters.js:127:22)
    at Queue.getJobs (/home/jakubp/Projects/guzzler/node_modules/bull/lib/getters.js:169:17)
    at Queue.getDelayed (/home/jakubp/Projects/guzzler/node_modules/bull/lib/getters.js:110:17)
    at getJobs (/home/jakubp/Projects/guzzler/src/crawling_jobs_socket.js:22:48)
    at Queue.<anonymous> (/home/jakubp/Projects/guzzler/src/crawling_jobs_socket.js:35:22)
    at emitOne (events.js:116:13)
    at Queue.emit (events.js:211:7)
    at /home/jakubp/Projects/guzzler/node_modules/bull/lib/job.js:411:15
From previous event:
    at /home/jakubp/Projects/guzzler/node_modules/bull/lib/job.js:409:42
    at <anonymous>
```

## Minimal, Working Test code to reproduce the issue.
The code that supposedly throws this is in handler of queue's local `'remove'` handler. It looks as follows:
```
const getJobs = async () => {
  const periodic = await periodicCrawlingQueue.getDelayed()
  const waiting = await crawlingQueue.getWaiting()
  const active = await crawlingQueue.getActive()
  const failed = await crawlingQueue.getFailed()
  return {
    periodic: periodic.map(mapQueueJobToSocketJob),
    waiting: waiting.map(mapQueueJobToSocketJob),
    active: active.map(mapQueueJobToSocketJob),
    failed: failed.map(mapQueueJobToSocketJob),
  }
}

crawlingQueue.on('removed', async () => {
  const jobs = await getJobs()
  socketioInstance.emit(EVENT_ON_CRAWLING_JOBS_UPDATED, jobs)
})
```
Note that I'm using two queues, `crawlingQueue` and `periodicCrawlingQueue`. When I remove 1st line of `getJobs` (one mentioned in stacktrace) the stacktrace starts mentioning the second line of `getJobs`.

## Bull version
3.5.2

**Comment by manast** [comment]
```crawlingQueue.on('removed', () => {
  const jobs = await getJobs()
  socketioInstance.emit(EVENT_ON_CRAWLING_JOBS_UPDATED, jobs)
})```
You are using await in a non async function, don't you get a compiler error?

**Comment by JakubPetriska** [comment]
Uhhh sorry, that was a copy paste error. Fixed the description.

**Comment by JakubPetriska** [comment]
@manast  I guess since it's coming from Bluebird the error will be removed with next version which does not contain Bluebird right?

**Comment by manast** [comment]
yes, that should be the case.

**Comment by JakubPetriska** [comment]
Ok thanks, then I guess we can close this.
