### ISSUE TITLE
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed (Sandbox.js)

### ISSUE THREAD

**Issue by ashkank83** [OptimalBits/bull#1281]
Bug report

## Description

I'm getting the following error when one (or maybe more) of my jobs (sandboxed processes) fail. It looks like this error completely kills the main thread and after it I have no solution other than restarting node again because it won't run any more jobs.
Error:
```
[2019-04-13 13:47:48] error: uncaughtException: Channel closed
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at childPool.retain.then.child (/myproject/node_modules/bull/lib/process/sandbox.js:12:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
This seems to be happening when the process times out (for example a SFTP collect job when the server is too slow to handshake or not available).
Sample error stack from a failed job:
```
[2019-04-13 13:47:48] error: job {"id":"X1904122003","name":"__default__","data":{"fileName":"X2003","sftpConnection":{"host":"x...}},"opts":{"jobId":"X2003","attempts":1,"delay":0,"timestamp":1555092633626},"progress":0,"delay":0,"timestamp":1555092633626,"attemptsMade":1,"failedReason":"Unexpected exit code: 7","stacktrace":["Error: Unexpected exit code: 7\n    at ChildProcess.exitHandler (/X/node_modules/bull/lib/process/sandbox.js:37:18)\n    at ChildProcess.emit (events.js:194:15)\n    at ChildProcess.EventEmitter.emit (domain.js:441:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)"],"returnvalue":null,"finishedOn":null,"processedOn":1555159668306} failed details: { Error: Unexpected exit code: 7
    at ChildProcess.exitHandler (/Xr/node_modules/bull/lib/process/sandbox.js:37:18)
    at ChildProcess.emit (events.js:194:15)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  [stack]:
   'Error: Unexpected exit code: 7\n    at ChildProcess.exitHandler (/X/node_modules/bull/lib/process/sandbox.js:37:18)\n    at ChildProcess.emit (events.js:194:15)\n    at ChildProcess.EventEmitter.emit (domain.js:441:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)',
  [message]: 'Unexpected exit code: 7' }
```

## Bull version
3.7.0
## Additional information
@alolis It looks like you have encountered a similar error. reading through your detailed post [here](https://github.com/OptimalBits/bull/issues/1098#issuecomment-439909638), I wonder if your fix would work for the issue I'm reporting here as well. I know you mentioned a PR in your post. has that already made and merged? I looked but couldn't find anything. Thanks

**Comment by alolis** [comment]
@ashkank83 looks related but I am not sure. Try to change the lines i mention in my post and give it a try! (You can just patch the library in your node_modules directly for a quick run)

**Comment by ashkank83** [comment]
@alolis Thanks a lot! it seems to be working. 
Removing the process in case of exit when child.exitCode !== null seems to be doing the job.

@manast : would you consider merging the PR?
Bug descriptions : When a child process exits unexpectedly, the child process will still stay in the childPool. It looks like when a next process gets the previously failed process from the child pool, it will fail with message: Error [Err_IPC_CHANNEL_CLOSED]: Channel closed.

Fix:
It looks like replacing following in process.js as suggested by @alolis [here](https://github.com/alolis/bull/blob/05df0aae3742f6538ee9e2c28b3e3762abeffad5/lib/process/sandbox.js#L51) will fix this issue:
```js
if (child.exitCode !== null) {
          childPool.remove(child);
        } else {
          childPool.release(child);
        }
```

**Comment by manast** [comment]
should be fixed in 3.8.0 release

**Comment by cgilindellmo** [comment]
Hi,

somehow I was able to reproduce this or similar issue with v3.8.1 with sandbox mode

/Users/test/project/node_modules/bull/lib/process/master.js:99
  throw err;
  ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:636:16)
    at Promise.resolve.then.err (/Users/test/project/node_modules/bull/lib/process/master.js:76:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by S0c5** [comment]
please refer to #1461

**Comment by phrozen** [comment]
I'm experiencing the same issue with Bull 3.12.1 jobs are immediately killed with stack-trace:

```
Error: Unexpected exit code: 12 signal: null
at ChildProcess.exitHandler (/X/node_modules/bull/lib/process/sandbox.js:41:13)
 at ChildProcess.emit (events.js:203:15)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

Seems like all solutions that have been given are already applied to master. Any chance anyone knows what is going on? (As additional information, I'm using hapi server and MacOSX in dev)
