### ISSUE TITLE
Possible infinite loop if BRPOPLPUSH fails ?

### ISSUE THREAD

**Issue by smennesson** [OptimalBits/bull#1304]
## Description

Hello today we faced a problem that seemed to be an infinite loop on Bull library.
Our service is hosted on Heroku with the Redis addon and today we reached the memory quota of the Redis DB.
What happened is that we had an enormous log stack saying this:
```
BRPOPLPUSH { ReplyError: OOM command not allowed when used memory > 'maxmemory'. 
    at parseError (/app/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12) 
    at parseType (/app/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14) 
  command: 
   { name: 'brpoplpush', 
     args: 
      [ 'bull:<name-of-our-job>:wait', 
        'bull:<name-of-our-job>:active', 
        '5' ] } } 
```

The log stack took up to 1gb in a few minutes until we fix the quota issue.

By looking a little bit to the code in `lib/queue.js`, it seems that the error on BRPOPLPUSH is ignored in `Queue.prototype.getNextJob`. So I guess that what happened is that the loop searching for new jobs to process was infinitely popping the error.

I don't have enough knowledge about how Bull internally works to propose a fix, but I think this is something that should be handled, maybe by detecting when there is several errors on BRPOPLPUSH and add a waiting duration when this happens to frequently.

## Bull version
v3.7.0 

(just seen that 3.8 is out ; it doesn't seem that it would be fixed in this version by reading the changelog)

**Comment by balexandre** [comment]
exactly same issue on the same circumstances: Heroku, Redis, BRPOPLPUSH :(

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/Cn3xS.png

**Comment by smennesson** [comment]
@balexandre actually reaching the Redis limit is not the real problem here. There could be a multiple reason causing your Redis db to be full and there is a few tools to show you what keys are taking the most memory space. So you can either clean a little bit or upgrade your plan.

Problem is that the Bull library is in an infinite loop when this occurs, generating a huge volume of logs, and ignoring the error, so we have no way to be warned this is occurring.

**Comment by kand617** [comment]
I have the same issue..... 

Is there some way to catch this error? 
And log a different message? 

I am not even sure where it's thrown from

**Comment by mmelvin0** [comment]
Seems to have been introduced in this commit: https://github.com/OptimalBits/bull/blob/f8ff3684915dd034492f10ba91fe5c2d5df0dbef/lib/queue.js#L893-L896

Perhaps the fix is simply to *not* swallow any errors here? Wouldn't this fire an error event on the queue if not swallowed?

**Comment by masiamj** [comment]
@mmelvin0 Did you receive a response or have any updates on this? Thanks!

**Comment by manast** [comment]
actually I think it would be as easy as only swalling "Connection is closed" error, since this error happens when we force to close the connection with redis, should be an easy fix.

**Comment by tnolet** [comment]
This blew up our logging pipeline too. Filled up our Papertrail daily limit in two minutes. I love Bull and would like to move on this quickly. @manast how can I or my team help fix this? We actually have an open ticket about this on our backlog because it can potentially break our production at https://checklyhq.com when this happens and we don't intervene manually

**Comment by manast** [comment]
if you provide a PR I will merge it quickly and make a release. It is as mentioned as simple as only swalling the error in case of connection is closed, and maybe add a small 5 seconds delay before trying again.

**Comment by tnolet** [comment]
@manast I will make a PR

**Comment by tnolet** [comment]
@manast I think this will do it. I refrained from adding a 5s delay because of unclear impact. I think not spamming the log is the first issue here. https://github.com/OptimalBits/bull/pull/1674

**Comment by tnolet** [comment]
Would love feedback or insights into the PR I mentioned above. This is still a significant risk to overwhelm any logging pipeline when things go south.

**Comment by manast-apsis** [comment]
This is high prio, will try to merge today.

**Comment by tnolet** [comment]
@manast-apsis thanks, let me know if I can help anywhere.

**Comment by tnolet** [comment]
@manast @manast-apsis Let me know what I need to do to get this merged. Thanks

**Comment by tnolet** [comment]
@manast @manast-apsis hope all is well, let me know if I can assist with merging the PR for this?

**Comment by manast** [comment]
The thing is that the current PR does not do anything valuable. I am not sure which solution is the best here, basically I think we need to just delay some seconds in the case of error, maybe can be configurable. But sometimes the connection will error with connection closed error since we are manually closing the queue, and in this case we do not want to delay so we need to check if the closing promise is set and in that case no delay.

**Comment by tnolet** [comment]
@manast what is your suggestion for moving this ticket forward? I have the feeling we are going in circles a bit. I would be happy to remove/close my PR in favour of a better solution. 

The reason I'm pushing this is that it is still a risk for many folks using logging solutions with hard limits.

**Comment by danielkv** [comment]
same problem here, only in production, using docker

**Comment by tnolet** [comment]
> The thing is that the current PR does not do anything valuable. I am not sure which solution is the best here, basically I think we need to just delay some seconds in the case of error, maybe can be configurable. But sometimes the connection will error with connection closed error since we are manually closing the queue, and in this case we do not want to delay so we need to check if the closing promise is set and in that case no delay.

@manast what do you mean when you say "we need to just delay some seconds". 

- What are we delaying? The `console.log()`
- What happens after the delay? We just log? Or do we take some other action?

I think I'm just really confused on the "delay" part. This will not solve spamming the logging channel. It will just spam with a delay...

**Comment by dobesv** [comment]
I posted a possible solution to this problem in #1746

**Comment by ostar0816** [comment]
@manast 
Can you please merge @dobesv 's PR? Or I think at least we have to swallow only `Connection is closed` error but throw others.

**Comment by manast** [comment]
@tnolet not sure if you are aware but this issue has been addressed some time ago https://github.com/OptimalBits/bull/pull/1974
 
Let me know if that is not the case.

**Comment by tnolet** [comment]
@manast I was not aware of this. Thanks for mentioning and fixing this! I will remove my thumbs down.

**Comment by Jimmycon210** [comment]
Hello, I am currently running into this. Finding that if the redis memory is full, `BRPOPLPUSH` fails spamming logs. This also prevents our app from processing jobs in the queue, causing the queue to remain full. 

Seems to be failing here: https://github.com/OptimalBits/bull/blob/develop/lib/queue.js#L1202

And the catch block doesn't catch anything, no error is thrown. We get stuck in an infinite loop.

**Comment by manast** [comment]
> Hello, I am currently running into this. Finding that if the redis memory is full, `BRPOPLPUSH` fails spamming logs. This also prevents our app from processing jobs in the queue, causing the queue to remain full.
> 
> Seems to be failing here: https://github.com/OptimalBits/bull/blob/develop/lib/queue.js#L1202
> 
> And the catch block doesn't catch anything, no error is thrown. We get stuck in an infinite loop.

If Redis is full, then the best is to delete some data by hand or upgrade the instance to one with more memory, most hosting provides seamless upgrade procedures.

**Comment by fdiwa-dev** [comment]
I hit similar Redis issues and ended up building MiniQueue — a REST job queue that runs on SQLite. No Redis, no cluster config, just an API key. Might save you the headache if your setup doesn't need the full Redis stack.

OSS here: https://github.com/fdiwa-dev/miniqueue
