### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by sibelius** [OptimalBits/bull#1335]
## Description

I'm getting some warnings when using bull

I've used this package to investigate more https://github.com/niftylettuce/max-listeners-exceeded-warning

Here are some errors when using this package:

```jsx
Error: Too many listeners of type "error" added to EventEmitter. Max is 10 and we've added 11.
    at Redis.addListener (webpack-internal:///../../node_modules/max-listeners-exceeded-warning/index.js:10:19)
    at Redis.once (events.js:290:8)
    at Promise (/app/node_modules/bull/lib/utils.js:41:14)
    at new Promise (<anonymous>)
    at Object.isRedisReady (/app/node_modules/bull/lib/utils.js:26:10)
    at isReady.then.then (/app/node_modules/bull/lib/queue.js:792:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Too many listeners of type "ready" added to EventEmitter. Max is 10 and we've added 11.
    at Redis.addListener (webpack-internal:///../../node_modules/max-listeners-exceeded-warning/index.js:10:19)
    at Redis.once (events.js:290:8)
    at Promise (/app/node_modules/bull/lib/utils.js:40:14)
    at new Promise (<anonymous>)
    at Object.isRedisReady (/app/node_modules/bull/lib/utils.js:26:10)
    at isReady.then.then (/app/node_modules/bull/lib/queue.js:792:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Too many listeners of type "ready" added to EventEmitter. Max is 10 and we've added 12.
    at Redis.addListener (webpack-internal:///../../node_modules/max-listeners-exceeded-warning/index.js:10:19)
    at Redis.once (events.js:290:8)
    at Promise (/app/node_modules/bull/lib/utils.js:40:14)
    at new Promise (<anonymous>)
    at Object.isRedisReady (/app/node_modules/bull/lib/utils.js:26:10)
    at isReady.then.then (/app/node_modules/bull/lib/queue.js:792:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Too many listeners of type "ready" added to EventEmitter. Max is 10 and we've added 13.
    at Redis.addListener (webpack-internal:///../../node_modules/max-listeners-exceeded-warning/index.js:10:19)
    at Redis.once (events.js:290:8)
    at Promise (/app/node_modules/bull/lib/utils.js:40:14)
    at new Promise (<anonymous>)
    at Object.isRedisReady (/app/node_modules/bull/lib/utils.js:26:10)
    at isReady.then.then (/app/node_modules/bull/lib/queue.js:792:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Too many listeners of type "ready" added to EventEmitter. Max is 10 and we've added 14.
    at Redis.addListener (webpack-internal:///../../node_modules/max-listeners-exceeded-warning/index.js:10:19)
    at Redis.once (events.js:290:8)
    at Promise (/app/node_modules/bull/lib/utils.js:40:14)
    at new Promise (<anonymous>)
    at Object.isRedisReady (/app/node_modules/bull/lib/utils.js:26:10)
    at isReady.then.then (/app/node_modules/bull/lib/queue.js:792:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Too many listeners of type "ready" added to EventEmitter. Max is 10 and we've added 15.
    at Redis.addListener (webpack-internal:///../../node_modules/max-listeners-exceeded-warning/index.js:10:19)
    at Redis.once (events.js:290:8)
    at /app/node_modules/ioredis/built/redis.js:320:19
    at process.nextTick (/app/node_modules/ioredis/built/connectors/StandaloneConnector.js:59:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
webpack-internal:///../../node_modules/max-listeners-exceeded-warning/index.js:20
    throw error;
    ^

Error: Too many listeners of type "ready" added to EventEmitter. Max is 10 and we've added 15.
    at Redis.addListener (webpack-internal:///../../node_modules/max-listeners-exceeded-warning/index.js:10:19)
    at Redis.once (events.js:290:8)
    at /app/node_modules/ioredis/built/redis.js:320:19
    at process.nextTick (/app/node_modules/ioredis/built/connectors/StandaloneConnector.js:59:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
``` 

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

kue has this method to make avoid this warning:
```jsx
queue.setMaxListeners(queue.getMaxListeners() + 1);
```

## Bull version
bull@3.9.1

**Comment by sibelius** [comment]
Some errors is caused by this one

https://github.com/OptimalBits/bull/blob/4d11352c1e/lib/utils.js#L25

`isRedisReady`, it is adding a lot of listeners without removing them

**Comment by manast** [comment]
what do you mean it is not removing them?

Just increase the listeners to avoid the warning, this is kind of a useless nodejs warning, a false positive in this case.

**Comment by sibelius** [comment]
how can we increase the listeners numbers?

**Comment by manast** [comment]
https://nodejs.org/dist/latest-v12.x/docs/api/events.html#events_eventemitter_defaultmaxlisteners
