### ISSUE TITLE
Trying to use reusing Redis connections throws

### ISSUE THREAD

**Issue by ronnyhaase** [OptimalBits/bull#1360]
## Description
I try to use the pattern for reusing Redis connections, but it throws immediately when running the app.

But it seems to connect to Redis, because it adds the `:stalled-check` dataset.
```
(node:4883) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined
    at /Users/ronnyhaase/Dropbox/Home/Projects/greina/greinad/queue/node_modules/bull/lib/queue.js:147:12
    at Queue.<anonymous> (/Users/ronnyhaase/Dropbox/Home/Projects/greina/greinad/queue/node_modules/bull/lib/queue.js:285:14)
    at /Users/ronnyhaase/Dropbox/Home/Projects/greina/greinad/queue/node_modules/bull/lib/queue.js:792:38
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:4883) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4883) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Minimal, Working Test code to reproduce the issue.
I reduced it to the bare minimum already, but it still doesn't work.
It works fine, when only passing `process.env.REDIS_URL` as second param. 
```js
const Queue = require('bull')
const Redis = require('ioredis')

const queueClient = new Redis(process.env.REDIS_URL)
const queueSubscriber = new Redis(process.env.REDIS_URL)

// This works fine:
// const Exchanges = new Queue('Foo', process.env.REDIS_URL)

const Foo = new Queue ('Foo', {
  createClient: function (type) {
    switch (type) {
      case 'client': return queueClient;
      case 'subscriber': return queueSubscriber;
      default: new Redis(process.env.REDIS_URL);
    }
  }
})

Exchanges.process((job, done) => done('ok'))
```

## Bull version
3.10.0

## Redis version
5 (dockerized with Docker Compose)

## Node version
12.3.1

**Comment by manast** [comment]
so you are not returning anything on the default case:
```
 default: new Redis(process.env.REDIS_URL);
```
