### ISSUE TITLE
Memory Leak / Error: undefined at Object.ensureErrorObject

### ISSUE THREAD

**Issue by Salakar** [OptimalBits/bull#144]
Notice memory usage increasing over time quote a lot and ran node debugger to find:

Debugger screens:
https://www.dropbox.com/s/tilf4tc6janjjcq/Screenshot%202015-07-17%2010.56.31.png?dl=0
https://www.dropbox.com/s/smkh1mqg0jjm026/Screenshot%202015-07-17%2011.00.40.png?dl=0

Seems to be something similar to https://github.com/hoodiehq/hoodie.js/issues/418 that issue on another repo. it's Bluebird/promise related.

Overnight with 2 queue items running every 5 secs memory was 2.7gb, and hundreds of thousands of those error strings and Arrays of Function stack traces too.

```
"Error: undefined
    at Object.ensureErrorObject (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/node_modules/bluebird/js/main/util.js:261:20)
    at Promise.module.exports.Promise._rejectCallback (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/node_modules/bluebird/js/main/promise.js:451:22)
    at Function.module.exports.Promise.reject.Promise.rejected (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/node_modules/bluebird/js/main/promise.js:195:9)
    at /Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:575:24
    at tryCatcher (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/node_modules/bluebird/js/main/promise.js:489:31)
    at Promise.module.exports.Promise._settlePromiseAt (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/nod"
Error
    at Promise.module.exports.Promise._captureStackTrace (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/node_modules/bluebird/js/main/debuggability.js:88:23)
    at Promise.module.exports.Promise._then (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/node_modules/bluebird/js/main/promise.js:218:13)
    at Promise.module.exports.Promise._passThroughHandler (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/node_modules/bluebird/js/main/finally.js:84:17)
    at Promise.module.exports.Promise.lastly.Promise.finally (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/node_modules/bluebird/js/main/finally.js:92:17)
    at Queue.processJobs (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:492:13)
    at /Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:493:18
    at Object.finallyHandler (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/node_modules/bluebird/js/main/finally.js:39"
   at Object.parse (native)
    at Function.Job.fromData (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/job.js:271:40)
    at /Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/job.js:39:18
From previous event:
    at Function.Job.fromId (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/job.js:37:56)
    at /Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:456:18
From previous event:
    at /Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:455:20
From previous event:
    at Queue.processStalledJobs (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:454:63)
    at Queue.processJobs (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:482:15)
From previous event:
    at Queue.processJobs (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:492:13)
    at /Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/que"
    at /Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:575:24
From previous event:
    at Queue.moveJob (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:571:58)
    at Queue.getNextJob (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:552:15)
    at /Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:483:18
From previous event:
    at Queue.processJobs (/Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:482:36)
    at /Users/Mike/Documents/Homestead/projects/hive/node_modules/bull/lib/queue.js:493:18
    at processImmediate [as _immediateCallback] (timers.js:358:17)"
```

**Comment by manast** [comment]
Is this 2 different bugs? a memory leak and an unexpected undefined error?, or is it that when this unexpected error happens a lot you get a high memory usage?

**Comment by Salakar** [comment]
Not sure because it doesn't error anywhere via console logs. I only seem them stacking up via node debug memory snapshot. If you run a node app with debugger up and bull queue and send something to it every 5 secs or so, take a mem snapshot after boot. Wait a few minutes then take another snapshot and do a compare option you'll see a load of strings and arrays as top usage, endlessly stacking up with these errors.

**Comment by Salakar** [comment]
It keeps going until node crashes with a FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory after a day or so.

I am using a custom redis client (ioredis) if that makes a difference, does seem to be promise / bull queue related though. (using ioredis as need failover/sentinel support for production setup)

**Comment by manast** [comment]
as current version we should be memory leak free.
