### ISSUE TITLE
Lua Redis() Error when Job added with options

### ISSUE THREAD

**Issue by oasis9217** [OptimalBits/bull#1488]
## Description

When a job is added queue, if there is an option that is supposed to be dynamic, add() returns an error. This has been working with Kue.js

Job add:
```
const queue = new Bull('MY QUEUE');
let priority = getPriorityFromSomewhere();  // can be undefined

queue.add({msg: 'hello world', {
        attemps: 1,
        removeOnComplete: true,
        priority: priority || 'normal'     // if priority is undefined, should be 'normal'
    })
    .catch(err) {
        console.error(err);
    }
```

This rejects with below. Note that priority was previously 'undefined' and feeded well as 'normal' 

```
{ ReplyError: ERR Error running script : 
@user_script:87: @user_script: 87: 
Lua redis() command arguments must be strings or integers at parseError (/home/node_modules/redis-parser/lib/parser.js:179:12) 
at parseType (/home/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14) 
command: { name: 'evalsha', args: [ '0a9a51ee96320953ec7bde8e63f3f060b9dac00c', '6', 'bull:MY QUEUE:wait', 'bull:MY QUEUE:paused', 'bull:MY QUEUE:meta-paused', 'bull:MY QUEUE:id', 'bull:MY QUEUE:delayed', 'bull:MY QUEUE:priority', 'bull:MY QUEUE:', '', '__default__', '{"msg":"hello world"}', '{"priority":"normal","attempts":1,"removeOnComplete":true,"delay":0,"timestamp":1569491449513}', '1569491449513', '0', '0', 'normal', 'LPUSH', '68c23833-d900-438e-b6de-eef124a76865' ] } }
```

if you do like below, Bull works find
```
const queue = new Bull('MY QUEUE');

let priority = getPriorityFromSomewhere();  // can be undefiend
priority = priority || 'normal'    // define it out of the ADD()

queue.add({msg: 'hello world', {
        attemps: 1,
        removeOnComplete: true,
        priority: priority 
    })
    .catch(err) {
        console.error(err);
    }
```

In addition, providing an object also does not work.
```
const queue = new Bull('MY QUEUE');
let priority = getPriorityFromSomewhere();  // can be undefiend

const options = {
       attemps: 1,
        removeOnComplete: true,
        priority: priority || 'normal'    // malicious part
}

queue.add({msg: 'hello world', options)       // pass options object
    .catch(err) {
        console.error(err);
    }
```

## Bull version
"3.11.0"

## Additional information
Node: 10.16.3

**Comment by oasis9217** [comment]
My bad, priority should be number not string 'normal' as Kue js
