### ISSUE TITLE
Bug: pausing queue does not wait for active jobs when using sandboxed processors

### ISSUE THREAD

**Issue by oavanruiten** [OptimalBits/bull#1613]
## Description

When restarting the main worker process, the queue needs to be paused. I am using the queue.pause() method, which should wait for any active jobs to complete before resolving. Right now it does not wait and resolves immediately, causing my jobs to be executed again after restart.

The bug is only related to sandboxed processors, as it works perfectly with a normal process function.

I created a simplified environment using a recurring job that runs every minute.
I use a mocked http post function to simulate an async http call that takes 5 seconds.

Start the node process using "node index.js"

When a job starts it will log "starting job...", when its done it will log "done!".

Terminate the node process right after you see "starting job" and you will notice that "done!" is never logged.

When using a process function instead, you will notice that "done!" is logged when terminating when the job is still running (see commented code in index.js).

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

index.js
```
const REDIS_URL =  process.env.REDIS_URL;

const path = require('path');
const Queue = require('bull');
const Redis = require('ioredis');
const { post } = require("./mock");

const client = new Redis(REDIS_URL);

let subscriber;

const options = {
  createClient(type) {
    switch (type) {
      case 'client':
        return client;
      case 'subscriber':
        return getOrCreateSubscriber();
      default:
        return new Redis(REDIS_URL);
    }
  },
};

const getOrCreateSubscriber = () => {
  if (!subscriber) subscriber = new Redis(REDIS_URL);
  return subscriber;
};

const queue = new Queue('tester', options);

let shuttingDown = false;

(async () => {
  try {
    queue.on('global:completed', async (jobId, result) => {
      const payload = JSON.parse(result);
      console.log("result", payload);
    });

    const shutdown = async (code) => {
      await queue.pause(true);
      console.log('Paused queue, exiting gracefully');
      setTimeout(async () => {
        client.quit(() => {
          console.log('Redis client disconnected');
          process.exit(code);
        });
      }, 1000);
    };

    process.on('SIGTERM', () => {
      console.log('Process SIGTERM');
      if (!shuttingDown) {
        shuttingDown = true;
        shutdown(0);
      }
    });

    process.on('SIGINT', () => {
      console.log('Process SIGINT');
      if (!shuttingDown) {
        shuttingDown = true;
        shutdown(0);
      }
    });

    const processor = path.join(__dirname, 'processor.js');

// comment this line if you want to use a normal process function
    queue.process('*', 1, processor);

// uncomment this line if you want to use a normal process function
//    queue.process(async function (job){
//      try {
//        console.log("starting job...");
//        await post().catch(error => console.log(error));
//        console.log("done!");
//        return job.data;
//      } catch (error) {
//        console.log("error", error);
//        throw error;
//      }
//    });
  } catch (error) {
    console.log("error", error);
  }
})();
```
processor.js
```
const { post } = require("./mock");

module.exports = async (job) => {
  try {
    console.log("starting job...");
    await post().catch(error => console.log(error));
    console.log("done!");
    return job.data;
  } catch (error) {
    console.log("error", error);
    throw error;
  }
};
```
mock.js
```
const post = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve();
    }, 5000);
  });
};

module.exports = {
  post
};
```

## Bull version

^3.10.0

## Additional information

I have tried using queue.close(), but this does not work either.

**Comment by oavanruiten** [comment]
@manast I have been doing a lot of testing and SIGTERM is indeed also killing the child processes like you mentioned here: https://github.com/OptimalBits/bull/issues/1521#issuecomment-546610735

I was able to tackle this by adding a listener for the SIGTERM (and SIGINT) event and doing nothing inside of that listener like this:
```
process.on('SIGINT', () => {
  console.log('SIGINT processor');
});
```

At this point everything was starting to look promising. The child processes were not killed anymore and the queue.pause() seemed to be working flawlessly as the following logs show:
```
Processors started.
starting job...
starting job...
^CProcess SIGINT
SIGINT processor
SIGINT processor
done!
done!
result { uuid: 2 }
result { uuid: 1 }
Paused queue, exiting gracefully
Redis client disconnected
```

Unfortunately after more testing the queue.pause() appears not to be working correctly every single time. Sometimes I get these logs:
```
Processors started.
starting job...
starting job...
^CProcess SIGINT
SIGINT processor
SIGINT processor
Paused queue, exiting gracefully
done!
done!
result { uuid: 1 }
result { uuid: 2 }
Redis client disconnected
```
The promise returned by queue.pause() sometimes resolves before the jobs complete. The reason why "result { uuid: x }" is still logged, is because of the timeout of 5 seconds before exiting the main worker process. If I remove this timeout , I get the following logs:
```
Processors started.
starting job...
starting job...
^CProcess SIGINT
SIGINT processor
SIGINT processor
Paused queue, exiting gracefully
Redis client disconnected
...-MacBook:... $ done!
/Users/.../node_modules/bull/lib/process/master.js:99
  throw err;
  ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:636:16)
    at Promise.resolve.then.result (/Users/.../node_modules/bull/lib/process/master.js:67:21)
done!
/Users/.../node_modules/bull/lib/process/master.js:99
  throw err;
  ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:636:16)
    at Promise.resolve.then.result (/Users/.../node_modules/bull/lib/process/master.js:67:21)
```
It seems like we are dealing with some kind of race condition that I am able to explain yet...

**Comment by oavanruiten** [comment]
Trying this with concurrency set to 12 and a mocked http request that takes between 1 to 5 seconds to resolve. The logs clearly show that pausing the queue does not work properly:

```
Starting tester processors...
Processors started.
Process 58958
starting job...
starting job...
starting job...
starting job...
starting job...
starting job...
starting job...
starting job...
starting job...
starting job...
starting job...
starting job...
done
^CProcess SIGINT
SIGINT processor
SIGINT processor
SIGINT processor
SIGINT processor
SIGINT processor
SIGINT processor
SIGINT processor
SIGINT processor
SIGINT processor
SIGINT processor
SIGINT processor
SIGINT processor
result { uuid: 1 }
done
result { uuid: 8 }
done
result { uuid: 9 }
done
done
result { uuid: 4 }
result { uuid: 7 }
done
result { uuid: 6 }
done
result { uuid: 5 }
done
result { uuid: 3 }
done
result { uuid: 10 }
Paused queue, exiting gracefully
done
result { uuid: 12 }
done
result { uuid: 2 }
done
result { uuid: 11 }
Redis client disconnected
exit processor
exit processor
exit processor
exit processor
exit processor
exit processor
exit processor
exit processor
exit processor
exit processor
exit processor
exit processor
```
The promise returned by queue.pause(true) resolves before all active jobs are completed. Having the timeout in place makes it work without any errors, but I feel like it should really wait for all jobs to complete before resolving... 

Reproducing this has been very straightforward, so hopefully somebody can help shed some more light on this...

**Comment by oavanruiten** [comment]
I followed the trail of queue.pause(true) into whenCurrentJobsFinished in queue.js:

```
/**
 * Returns a promise that resolves when active jobs are finished
 *
 * @returns {Promise}
 */
Queue.prototype.whenCurrentJobsFinished = function() {
  if (!this.bclientInitialized) {
    // bclient not yet initialized, so no jobs to wait for
    return Promise.resolve();
  }

  //
  // Force reconnection of blocking connection to abort blocking redis call immediately.
  //
  const forcedReconnection = redisClientDisconnect(this.bclient).then(() => {
    return this.bclient.connect();
  });

  return Promise.all([this.processing[0]]).then(() => {
    return forcedReconnection;
  });
};
```
Why is only the first element of the this.processing array used and not the entire array?

Using Promise.all(this.processing) seems to fix my issue entirely.

```
/**
 * Returns a promise that resolves when active jobs are finished
 *
 * @returns {Promise}
 */
Queue.prototype.whenCurrentJobsFinished = function() {
  if (!this.bclientInitialized) {
    // bclient not yet initialized, so no jobs to wait for
    return Promise.resolve();
  }

  //
  // Force reconnection of blocking connection to abort blocking redis call immediately.
  //
  const forcedReconnection = redisClientDisconnect(this.bclient).then(() => {
    return this.bclient.connect();
  });

  return Promise.all(this.processing).then(() => {
    return forcedReconnection;
  });
};
```

**Comment by oavanruiten** [comment]
This issue is not a bug. I will close this and open a question to find out why `whenCurrentJobsFinished` is only waiting for 1 job to complete and not all active jobs.
