### ISSUE TITLE
Data does not support bigint.

### ISSUE THREAD

**Issue by arul-sargunam** [OptimalBits/bull#1707]
If the data object has Bigint  Bull Job add throws error during serialization.
[2020-04-22T09:11:18.069Z] (node:24128) UnhandledPromiseRejectionWarning: TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at Job.toData (C:\Users\arul\git\plas_algo\node_modules\bull\lib\job.js:160:20)
    at addJob (C:\Users\arul\git\plas_algo\node_modules\bull\lib\job.js:64:23)
    at C:\Users\arul\git\plas_algo\node_modules\bull\lib\job.js:78:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Is there any possibility of supporting this or do I need to convert it to string ?

**Comment by gabegorelick** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

> Using JSON.stringify() with any BigInt value will raise a TypeError as BigInt values aren't serialized in JSON by default. However, you can implement your own toJSON method if needed

That being said, Bull could probably handle this if it's a common request.

**Comment by PixeliumTN** [comment]
Any news regarding this request ?

**Comment by manast** [comment]
@PixeliumTN no plans to implement this for now, but as @gabegorelick explained you can implement this in user code.
