### ISSUE TITLE
BRPOPLPUSH ReplyError: UNBLOCKED force unblock from blocking operation, instance state changed (master -> replica?)

### ISSUE THREAD

**Issue by sinisavukovic** [OptimalBits/bull#1738]
## Description
Hello.  
I've been dealing with this issue for a couple of days now and I've run out of ideas on how to fix this. I keep getting this error randomly.

First error that appears:
```
BRPOPLPUSH ReplyError: UNBLOCKED force unblock from blocking operation, instance state changed (master -> replica?)
    at parseError (/home/node/app/node_modules/redis-parser/lib/parser.js:179:12) 
    at parseType (/home/node/app/node_modules/redis-parser/lib/parser.js:302:14) 
  command: 
   { name: 'brpoplpush', 
     args: 
      [ 'bull:<name-of-our-job>:wait', 
        'bull:<name-of-our-job>:active', 
        '5' ] } } 
```
following with multiple READONLY errors for each queue that is registered
```
BRPOPLPUSH  ReplyError: READONLY You can't write against a read only replica. 
    at parseError (/home/node/app/node_modules/redis-parser/lib/parser.js:179:12) 
    at parseType (/home/node/app/node_modules/redis-parser/lib/parser.js:302:14) 
  command: 
   { name: 'brpoplpush', 
     args: 
      [ 'bull:<name-of-our-job>:wait', 
        'bull:<name-of-our-job>:active', 
        '5' ] } } 
```
## Minimal, Working Test code to reproduce the issue.

```
const createClient = (): Redis => {
  return new IORedis({
    port: 6379,
    host: "redis",
    enableReadyCheck: false,
    maxRetriesPerRequest: null,
    reconnectOnError: (err): boolean | void => {
      if (err.message.includes("READONLY")) {
        // Only reconnect when the error contains "READONLY"
        return true; // or `return 1;`
      }
    },
  });
}


const client = createClient();
const subscriber = createClient();
const defaultClient = createClient();

const createQueue(name: string, options?: QueueOptions): Queue {
    return new Bull(name, {
      createClient: (type): Redis => {
        switch (type) {
          case 'client':
            return client;
          case 'subscriber':
            return subscriber;
          case 'bclient':
            return defaultClient;
          default:
            throw new Error('Unexpected connection type: ', type);
        }
      },
      ...options
    });
  };

const queue = BullLoader.createQueue('my-queue-name')

await queue.add({}, {
      attempts: 1,
      backoff: 1,
      removeOnComplete: true,
      removeOnFail: true
    })

queue.process(`./job.js`)

//job.js file
module.exports = async (job)=> {
   //job logic
   return Promise.resolve();
}
```

## Bull version
3.14.0

## Additional information
Redis version is 5.0.9. I've also tried with Redis 6, but same thing happend
App is hosted on DigitalOcean under Docker.

**Comment by manast** [comment]
somehow the redis instance you are connected to is acting as a slave, thats why you get that error from redis, but I have no idea how you ended in that situation...

**Comment by sinisavukovic** [comment]
I've managed to prevent this error from happening.
I've set `replica-read-only` to  **no** in redis configuration

I'm still not sure what happens so that redis wants to read from slate when replica is not set.

**Comment by suraj-pareek** [comment]
I have also set replica-read-only to no in Redis configuration but it didn't work for me.
Can anyone help me to find the root cause of this issue and fix of this issue?

**Comment by lakshmankashyap** [comment]
Hi, So what is the main solution for this? can you share?
