### ISSUE TITLE
Trigger a job from a difference server

### ISSUE THREAD

**Issue by aberba** [OptimalBits/bull#1778]
I would like to implement bull job queue using two server instances, an app server and a jobs server. I'm not sure how its possible to trigger a job from the jobs server using Bull. Can you please show the API for doing something like that?

Also how do I schedule a job to be executed at a future time? I can't find such an API. Maybe I'm missing something. 

I've been using Agenda so its why I'm asking these sort of question, so please bare with me. 

Example pseudocode of what I'm trying to don:

App server:
```js
// this is where certain job will be triggered to run
job.schedule(time, "jobname");
job.runEvery("2 days", "jobName");
```

Remote server:
```js
/// this is where the actual jobs are defines
```

**Comment by gustawdaniel** [comment]
I am trying to do the same scenario. I finished with:

```
W20201027-19:24:44.805(1)? (STDERR) (node:75455) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
W20201027-19:24:44.806(1)? (STDERR)     at Array.forEach (<anonymous>)
W20201027-19:24:44.806(1)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20201027-19:24:44.806(1)? (STDERR)     at packages/ejson/ejson.js:600:22
W20201027-19:24:44.807(1)? (STDERR)     at Array.forEach (<anonymous>)
W20201027-19:24:44.807(1)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20201027-19:24:44.807(1)? (STDERR)     at packages/ejson/ejson.js:600:22
W20201027-19:24:44.807(1)? (STDERR)     at Array.forEach (<anonymous>)
W20201027-19:24:44.808(1)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20201027-19:24:44.808(1)? (STDERR)     at packages/ejson/ejson.js:600:22
W20201027-19:24:44.808(1)? (STDERR)     at Array.forEach (<anonymous>)
W20201027-19:24:44.809(1)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20201027-19:24:44.809(1)? (STDERR)     at packages/ejson/ejson.js:600:22
W20201027-19:24:44.809(1)? (STDERR)     at Array.forEach (<anonymous>)
W20201027-19:24:44.809(1)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20201027-19:24:44.810(1)? (STDERR)     at packages/ejson/ejson.js:600:22
W20201027-19:24:44.810(1)? (STDERR)     at Array.forEach (<anonymous>)
W20201027-19:24:44.810(1)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20201027-19:24:44.811(1)? (STDERR)     at packages/ejson/ejson.js:600:22
W20201027-19:24:44.811(1)? (STDERR)     at Array.forEach (<anonymous>)
W20201027-19:24:44.811(1)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20201027-19:24:44.811(1)? (STDERR)     at packages/ejson/ejson.js:600:22
W20201027-19:24:44.812(1)? (STDERR)     at Array.forEach (<anonymous>)
W20201027-19:24:44.812(1)? (STDERR) (node:75455) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
```
