### ISSUE TITLE
 Cannot read property 'id' of null

### ISSUE THREAD

**Issue by Bahramibh** [OptimalBits/bull#1801]
TypeError: Cannot read property 'id' of null
    at formatJob (/home/me/Desktop/nodetest/node_modules/bull-board/routes/getDataForQeues.js:27:13)
    at Array.map (<anonymous>)
    at /home/me/Desktop/nodetest/node_modules/bull-board/routes/getDataForQeues.js:73:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async getDataForQeues (/home/me/Desktop/nodetest/node_modules/bull-board/routes/getDataForQeues.js:57:18)
    at async handler (/home/me/Desktop/nodetest/node_modules/bull-board/routes/queues.js:5:5)

**Comment by Bahramibh** [comment]
index : 
```
const express = require("express");
const { setQueues, UI, createQueues } = require("bull-board");
const app = express();
const { queue } = require("./fresh.queue");

queue.process(function (job, done) {
	// console.log(job.progress);
	console.log(job.data);
	done();
});

// for (let i = 0; i < 3; i++) {
// 	queue.add({ c: c++ }, { removeOnComplete: true });
// }

// setInterval(() => {
// 	queue.add({ c: c++ }, { removeOnComplete: true });
// }, 100);

setInterval(() => {
	console.log("-----");
}, 1000);

setQueues(queue);
app.use("/", UI);
const PORT = 1231;
app.listen(PORT, function () {
	console.log("running on port ", PORT);
});

module.exports = { queue };

```

feed : 
```
let Queue = require("bull");
let c = 1;
const { queue } = require("./fresh.queue");

console.log("feed start");

// for (let i = 0; i < 1000; i++) {
// 	queue.add({ c: c++ }, { removeOnComplete: true });
// }

setInterval(() => {
	console.log("added: ", c++);
	queue.add({ c }, { removeOnComplete: true });
}, 10);
```

and simple queue : 
```
let Queue = require("bull");
let queue = new Queue("queue", "redis://127.0.0.1:6379");

module.exports = { queue };
```

**Comment by Bahramibh** [comment]
throw error 3 times 
``

**Comment by Bahramibh** [comment]
{ c: 4065 }
{ c: 4066 }
{ c: 4067 }
{ c: 4068 }
{ c: 4069 }
{ c: 4070 }
-----
{ c: 4071 }
TypeError: Cannot read property 'id' of null
    at formatJob (/home/amir/Desktop/nodetest/node_modules/bull-board/routes/getDataForQeues.js:27:13)
    at Array.map (<anonymous>)
    at /home/amir/Desktop/nodetest/node_modules/bull-board/routes/getDataForQeues.js:73:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async getDataForQeues (/home/amir/Desktop/nodetest/node_modules/bull-board/routes/getDataForQeues.js:57:18)
    at async handler (/home/amir/Desktop/nodetest/node_modules/bull-board/routes/queues.js:5:5)
{ c: 4072 }
{ c: 4073 }
{ c: 4074 }
{ c: 4075 }
{ c: 4076 }
{ c: 4077 }

**Comment by Bahramibh** [comment]
throw error 3 times in : 
```
{ c: 4065 }
{ c: 4066 }
{ c: 4067 }
{ c: 4068 }
{ c: 4069 }
{ c: 4070 }
-----
{ c: 4071 }
TypeError: Cannot read property 'id' of null
    at formatJob (/home/amir/Desktop/nodetest/node_modules/bull-board/routes/getDataForQeues.js:27:13)
    at Array.map (<anonymous>)
    at /home/amir/Desktop/nodetest/node_modules/bull-board/routes/getDataForQeues.js:73:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async getDataForQeues (/home/amir/Desktop/nodetest/node_modules/bull-board/routes/getDataForQeues.js:57:18)
    at async handler (/home/amir/Desktop/nodetest/node_modules/bull-board/routes/queues.js:5:5)
{ c: 4072 }
{ c: 4073 }
{ c: 4074 }
{ c: 4075 }
{ c: 4076 }
{ c: 4077 }
```

**Comment by Bahramibh** [comment]
this error throw when main file (job processor ) stop , then restart.
but feed , send job to queue

**Comment by manast** [comment]
The error comes from one of your source files, "getDataForQeues", please review.
