### ISSUE TITLE
Unable to create Queue from Google Cloud Run Redis

### ISSUE THREAD

**Issue by Ritz90** [OptimalBits/bull#1913]
I'm trying to setup my redis bull on Google Cloud run. Locally everything works.

I use the following code when the server starts:

const client = redis.createClient('6379', '10.103.YYY.YYY');
This seems to be working. I don't receive any error on startup.

When I try to launch a job with Bull like:

             const actionQueue = new Bull(uuid(), {
                redis: {
                    port: 6379, host: '10.103.YYY.YYY', tls: {
                        servername: '10.103.YYY.YYY'
                    }
                }
            });
         
            await actionQueue.add();

            actionQueue.process(async (job) => {
                return this._job();
            });

            actionQueue.on('completed', async (job, actionId) => {
                console.log(`Job completed with result ${actionId}`);
            });

            actionQueue.on("failed", (job, error) => {
                console.log(job.id, error);
            });

Logs:

2020-11-21T14:55:35.794783Z <rejected> Error: connect ECONNREFUSED 127.0.0.1:6379
Standaard
2020-11-21T14:55:35.794791Z at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
Standaard
2020-11-21T14:55:35.794798Z errno: 'ECONNREFUSED',
Standaard
2020-11-21T14:55:35.794804Z code: 'ECONNREFUSED',
Standaard
2020-11-21T14:55:35.794810Z syscall: 'connect',
Standaard
2020-11-21T14:55:35.794816Z address: '127.0.0.1',
Standaard
2020-11-21T14:55:35.794822Z port: 6379
Standaard
2020-11-21T14:55:35.794828Z }
Standaard
2020-11-21T14:55:35.794834Z}
Standaard
2020-11-21T14:55:35.794987Z The error was: Error: connect ECONNREFUSED 127.0.0.1:6379
Standaard
2020-11-21T14:55:35.794994Z at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
Standaard
2020-11-21T14:55:35.795Z errno: 'ECONNREFUSED',
Standaard
2020-11-21T14:55:35.795006Z code: 'ECONNREFUSED',
Standaard
2020-11-21T14:55:35.795011Z syscall: 'connect',
Standaard
2020-11-21T14:55:35.795017Z address: '127.0.0.1',
Standaard
2020-11-21T14:55:35.795022Z port: 6379
Standaard
2020-11-21T14:55:35.795028Z}

**Comment by manast** [comment]
I find highly unlikely that this setting will work, besides it is not the same as your example when you connected using the redis client directly:
```ts
tls: {
                    servername: '10.103.YYY.YYY'
                }
```
