### ISSUE TITLE
Calling queue constructor w/o a name causes a background promise rejection

### ISSUE THREAD

**Issue by osher** [OptimalBits/bull#1958]
## Description
Bull Queue constructor does not require a name, however, without a name an internal promise rejects without the user being able to do anything about it.

This behavior will soon be terminal.

```
> (node:24088) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:331:9)
    at Queue.base64Name (c:\generator\node_modules\bull\lib\worker.js:38:19)
    at Queue.clientName (c:\generator\node_modules\bull\lib\worker.js:42:40)
    at c:\generator\node_modules\bull\lib\worker.js:16:51
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:24088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
https://github.com/OptimalBits/bull/pull/1956

## Bull version
`bull@3.20.0`

## Additional information

keep up the good work! <3

**Comment by manast** [comment]
Can you provide a test case?

**Comment by manast** [comment]
Closing due to lack of feedback.

**Comment by osher** [comment]
wh...?
