### ISSUE TITLE
Error: Connection is closed after close()

### ISSUE THREAD

**Issue by m7x333** [OptimalBits/bull#2045]
## Description
hello, 
```javascript
export async function addFetchFollowers(
  userId: string,
  request: RequestDocument,
  followersQueue: Bull.Queue
) {
  const job = await followersQueue.add({
    userId,
    request: request.request,
  });
}
```
```javascript
for (const userId of userIdsToProcess) {
      const workerResponse = addFetchFollowers(
        userId._id,
        request,
        followersQueue
      );
}
followersQueue.close();
```
with userIdsToProcess is about of 200k records sometimes this happening:
```
(node:143009) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/opt/crawler/node_modules/ioredis/built/redis/event_handler.js:183:25)
    at Socket.<anonymous> (/opt/crawler/node_modules/ioredis/built/redis/event_handler.js:150:20)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:327:22)
    at TCP.<anonymous> (net.js:673:12)
```

seems like connection is closed with some jobs still wait for add to queue
is any recommendation for proper connection closing, may be i need to wait somehow?

## Bull version
3.22.0

**Comment by manast** [comment]
you are not awaiting the call to ```addFetchFollowers``` so you close the connection before the jobs are actually added.
If you are going to add a lot of jobs I recommend you use Promise.all or batch in order to get better performance.
