### ISSUE TITLE
sandbox job stalled

### ISSUE THREAD

**Issue by dtboy1995** [OptimalBits/bull#2136]
## Description

follow the doc https://github.com/OptimalBits/bull#separate-processes
**You can run blocking code without affecting the queue (jobs will not stall).**
but i got stalled event and woker stop. i have to restart my app to resume job.

## Minimal, Working Test code to reproduce the issue.
```js
const hitRtaResourceQueue = new Queue('hitRtaResourceQueue', {
    defaultJobOptions: {
        removeOnComplete: true
    },
    settings: {
        maxStalledCount: 60
    }
})
hitRtaResourceQueue.process(hitRtaResourceConcurrency, path.join(__dirname, '/hit-rta-resource.js'))
hitRtaResourceQueue.on('failed', async (job, err) => {
    let { data } = job
    try {
        await new Promise((resolve) => setTimeout(resolve, 3 * 1000))
        await job.retry()
        let error_str = util.format(err)
        await JobError.create({
            name: 'hitRtaResourceQueue',
            data,
            error_str
        })
    } catch (err) {
        logger.error(err)
    } finally {
        let { _id } = data
        await Task.findByIdAndUpdate(_id, {
            status: 'FAILED'
        })
    }
})

let Queues = {
   hitRtaResourceQueue,
}

Object.keys(Queues).forEach((name) => {
    Queues[name].on('error', (err) => {
        appendLog(name, err)
    })
    Queues[name].on('stalled', (job) => {
        appendLog(name, { id: job.id, name: job.name, message: 'stalled' })
    })
})

```

### /hit-rta-resource.js
// any require
module.exports = async function (job) {
    let { _id } = job.data
    try {
        await redis.connect()
        await mongoose.connect(config.mongodb_main, { useNewUrlParser: true })
        // just upload many zips (for of serial not Promise.all)
    } catch (err) {
        logger.error(err)
        throw err
    } finally {
        clearTimeout(timer)
        mongoose.disconnect()
        redis.disconnect(false)
    }
}

> There will be stagnant tasks every day. You can only restart the main application to continue running

thanks

**Comment by manast** [comment]
You are not providing the code that actually fetches jobs from the queue, but I guess the problem is that you need to "extend" the job lock which you need to do if the job does take more than the default 30 seconds lock duration. The method for extending the lock was missing in Bull but I just added it and updated the documentation here: https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#manually-fetching-jobs

So you can use the latest Bull release and check if it solves your issue.

**Comment by dtboy1995** [comment]
@manast Thank you for your prompt reply

but i dont use `Manually fetching jobs`
I just use the most common patterns

```js
let result = await HitResult.create(hit_result)
    let { _id } = result
    await hitRtaResourceQueue.add({
        _id
    }, {
        jobId: _id
    })
```

**Comment by dtboy1995** [comment]
I just want to know under what circumstances, the job will hang indefinitely and must restart the server to work normally. Is the CPU utilization too high or insufficient memory (sandboxed mode)

If I want the task to succeed anyway, can I use the following configuration? 
```
const testQueue = new Queue('_testQueue', {
    defaultJobOptions: {
        removeOnComplete: true,
        attempts: Number.MAX_SAFE_INTEGER,
        backoff: 5 * 1000
    },
    settings: {
        stalledInterval: 30 * 1000,
        // stalledInterval: 5 * 60 * 1000,
        maxStalledCount: Number.MAX_SAFE_INTEGER
    }
})
```
thank you. I hope you can give me some suggestions

**Comment by dtboy1995** [comment]
Bull Very robust，I tested it on the machine this afternoon and did not reproduce the server error

### job.js
```js
const moment = require('moment')
const mongoose = require('mongoose')

module.exports = async function (job) {
    let { _id } = job.data
    try {
        await mongoose.connect('mongodb://localhost:27017/foo')
        console.log(process.pid)
        console.log(moment().format('YYYY-MM-DD HH:mm:ss:SSS'))
        // let x = 100;
        // for (let i = 0; i < x; i++) {
        //     Buffer.alloc(1024 * 1024)
        // }
        await new Promise((resolve) => setTimeout(resolve, 60 * 1000))
        if (moment().minutes() >= 10) {

        } else {
            process.exit(7)
        }
    } catch (err) {
        throw err
    } finally {
        mongoose.disconnect()
    }
}
```

### app.js
```js
const Koa = require('koa')

const app = new Koa()
const Queue = require('bull')

const testQueue = new Queue('_testQueue', {
    defaultJobOptions: {
        removeOnComplete: true,
        attempts: Number.MAX_SAFE_INTEGER,
        backoff: 5 * 1000
    },
    settings: {
        stalledInterval: 30 * 1000,
        // stalledInterval: 5 * 60 * 1000,
        maxStalledCount: Number.MAX_SAFE_INTEGER
    }
})

testQueue.on('completed', (job) => {
    console.log('completed', job.data);
})

testQueue.on('failed', (job, err) => {
    console.log('failed', job.data, err);
})

testQueue.on('stalled', (job) => {
    console.log('stalled', job.data);
})

testQueue.on('error', (err) => {
    console.log('error', err);
})

testQueue.process(3, __dirname + '/job.js')
// testQueue.process(3, require('./job'))

app.listen(3000, async (err) => {
    console.log(process.pid)
    // console.log(Number.MAX_VALUE);
    // await testQueue.add({ _id: 'keyboard_Z' })
    // await testQueue.add({ _id: 'keyboard' })
    // await testQueue.add({ _id: 'keyboard' })
})
```
it works well

**Comment by dtboy1995** [comment]
ref to https://github.com/OptimalBits/bull#using-promises
> transcoding video
Since CPU intensive programs can also be executed inside applications, what is the use of sandboxes? thanks

**Comment by manast** [comment]
> I just want to know under what circumstances, the job will hang indefinitely and must restart the server to work normally. Is the CPU utilization too high or insufficient memory (sandboxed mode)

The job will not hang indefinitely from BullMQ's side, it will be in active status until the worker completes (or fails). However, if the job is very CPU intensive, then the worker will not be able to renew the job lock every 15 seconds, and then the job will be eventually marked as stalled and moved back to the wait status or failed if it has stalled more than the maximum amount of stalls allowed.

**Comment by manast** [comment]
@dtboy1995 I recommend you that you create the connection to mongo outside of the processor handler, so that you can reuse the same connection for all the jobs:

```ts
const connection = mongoose.connect('mongodb://localhost:27017/foo');

module.exports = async function (job) {
    let { _id } = job.data
    try {
        await connection;
  ```

**Comment by dtboy1995** [comment]
> @dtboy1995 I recommend you that you create the connection to mongo outside of the processor handler, so that you can reuse the same connection for all the jobs:
> 
> ```ts
> const connection = mongoose.connect('mongodb://localhost:27017/foo');
> 
> module.exports = async function (job) {
>     let { _id } = job.data
>     try {
>         await connection;
> ```

Thank you for your advice, but I run it in a sandbox, which will also be reused?
```js
fooQueque.process(n, __dirname + '/foo-job.js')
```

**Comment by manast** [comment]
Yes but the code for connecting to mongodb will be called every time a job is processed...

**Comment by dtboy1995** [comment]
Is there any way to make the queue retry indefinitely until the task succeeds (workers don't stalled)....

**Comment by dtboy1995** [comment]
### error log
```
{
        "_id" : ObjectId("6122d88207da952989fe641a"),
        "name" : "hitRtaResourceQueue",
        "data" : {
                "_id" : "61229e4842492020d341b446"
        },
        "error_str" : "Error: Unexpected exit code: 7 signal: null\n    at ChildProcess.exitHandler (/root/apps/hit-api/node_modules/bull/lib/process/sandbox.js:47:13)\n    at ChildProcess.emit (events.js:326:22)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)",
        "created_at" : ISODate("2021-08-22T23:06:42.442Z"),
        "updated_at" : ISODate("2021-08-22T23:06:42.442Z")
}
```
