### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT at TLSSocket

### ISSUE THREAD

**Issue by dipayan-solutelabs** [OptimalBits/bull#2217]
## Description
Running into this creepy problem while trying to initiate a connection to Digital Ocean redis via bull. I have tried the fixes mentioned in other issues (for eg : https://github.com/OptimalBits/bull/issues/1464), unfortunately it does not seem to work well here.

## Minimal, Working Test code to reproduce the issue.
```
BullModule.forRoot({
      redis: 
      {
        username: REDIS_USERNAME,
        password: REDIS_PASSWORD,
        host: REDIS_QUEUE_URL,
        port: Number(REDIS_PORT),
        connectTimeout: 30000,
        tls: {}
      }
    }),
```

### Error in details
```
(node:200475) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at TLSSocket.<anonymous> (/home/dipayan/Documents/code/easyvest/easyvest-backend-apis/node_modules/ioredis/built/redis/index.js:308:37)
    at Object.onceWrapper (events.js:482:28)
    at TLSSocket.emit (events.js:376:20)
    at TLSSocket.emit (domain.js:470:12)
    at TLSSocket.Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
(node:200475) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

### Bull version
3.22.0

**Comment by dashcraft** [comment]
I was able to fix this problem using the following config...

```
new Queue('q_name', 'rediss://someurlgoeshere', {
 redis: {
   tls: {}
 }
} )
```

I didn't have to maintain any connection timeout issues or anything like that.
This is literally all i had to do, using digital oceans redis/database instance which provides
an rediss url
