### ISSUE TITLE
[BUG]Errors under Cluster

### ISSUE THREAD

**Issue by WumaCoder** [OptimalBits/bull#2344]
## Description
I'm using queue An error occurred while adding (data).

## Minimal, Working Test code to reproduce the issue.
Redis cluster：

```js
    console.log('start')

    const t  = await pdfQueue.add({
        title: 'hello',
        content: 'zzzz',
        day: '2020-01-01',
        files:[
            {
                key: 'https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png',
                name: 'xxx',
            }
        ]
    });

    console.log({t});
```

## Bull version
4.8.2

## Additional information

error
```
12|pre  | [ReplyError: ERR 'EVALSHA' command keys must in same slot
12|pre  |   at parseError (/root/qihuiqiang/teacher_pre/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:179:12)
12|pre  |   at parseType (/root/qihuiqiang/teacher_pre/node_modules/_redis-parser@3.0.0@redis-parser/lib/parser.js:302:14)
12|pre  | ] {
12|pre  |   command: {
12|pre  |     name: 'evalsha',
12|pre  |     args: [
12|pre  |       '8f55ae4a3be429c6d38c5d5db3e80edf89197b64',
12|pre  |       '6',
12|pre  |       'bull:sign-synthesis:wait',
12|pre  |       'bull:sign-synthesis:paused',
12|pre  |       'bull:sign-synthesis:meta-paused',
12|pre  |       'bull:sign-synthesis:id',
12|pre  |       'bull:sign-synthesis:delayed',
12|pre  |       'bull:sign-synthesis:priority',
12|pre  |       'bull:sign-synthesis:',
12|pre  |       '',
12|pre  |       '__default__',
12|pre  |       '{"title":"hello","content":"zzzz","day":"2020-01-01","files":[{"key":"https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png","name":"xxx"}]}',
12|pre  |       '{"removeOnFail":{"age":43200,"count":10},"removeOnComplete":{"age":3600},"attempts":1,"delay":0,"timestamp":1650632214433}',
12|pre  |       '1650632214433',
12|pre  |       '0',
12|pre  |       '0',
12|pre  |       '0',
12|pre  |       'LPUSH',
12|pre  |       '1c3d0095-6682-436e-ad90-e8245199b896'
12|pre  |     ]
12|pre  |   }
12|pre  | }
```

**Comment by MrWWY** [comment]
When I connect redis cluster , I have the same problem,  "ReplyError: ERR 'EVAL' command keys must in same slot" 
How do you solve it? thanks

**Comment by manast** [comment]
Wrap your queue name in curly braces: "{my queue}"
