### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by jozsi** [OptimalBits/bull#241]
I've ran `npm test` on the current `master` branch (8bea8f0800caaf9ec2a6f408372e093cc79b76c0), but there are 13 tests failing:
```
  86 passing (3m)
  2 pending
  13 failing

  1) Cluster should process delayed jobs in correct order:
     Uncaught Error: expected 0 to be below undefined
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.lessThan.Assertion.below (node_modules/expect.js/index.js:313:10)
      at Function.below (node_modules/expect.js/index.js:499:17)
      at workerMessageHandler (test/test_cluster.js:103:27)
      at Worker.workerMessageHandlerWrapper (test/test_cluster.js:45:5)
      at handleMessage (internal/child_process.js:689:10)
      at Pipe.channel.onread (internal/child_process.js:440:11)

  2) Priority queue processes jobs by priority:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  3) Priority queue processes several stalled jobs when starting several queues:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  4) Priority queue process several jobs serially:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  5) Priority queue Cleaner should clean two jobs from the queue:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  6) Priority queue Cleaner should only remove a job outside of the grace period:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  7) Priority queue Cleaner should clean all failed jobs:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  8) Priority queue Cleaner should clean a job without a timestamp:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  9) Queue  a worker processes several stalled jobs when starting several queues:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  10) Queue  a worker process several jobs serially:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  11) Queue Delayed jobs should process delayed jobs with exact same timestamps in correct order (FIFO):
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  12) Queue Concurrency process should process job respecting the concurrency set:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  13) Queue "after each" hook for "should process job respecting the concurrency set":
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
```

Most of them fail with unhandled rejections (e.g. `Unhandled rejection Error: expected 3 to equal 4`).
I am using Redis v3.0.7 with `FLUSHALL` prior to running the tests.

**Comment by manast** [comment]
tests have been improved in https://github.com/OptimalBits/bull/tree/v1.0.0-rc
