### ISSUE TITLE
ReplyError: ERR Syntax error, try CLIENT (LIST | KILL ip:port)

### ISSUE THREAD

**Issue by romilynxt** [OptimalBits/bull#2423]
```
const Queue = require('bull');
const waQueue = new Queue('Sending Email', { redis: { host: process.env.REDIS_HOST, password: process.env.REDIS_PASS, port: 6379 }, limiter: { max: 100, duration: 5000 } });
```

After running nom start I am getting the error: 

```
ReplyError: ERR Syntax error, try CLIENT (LIST | KILL ip:port)
    at parseError (\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'client',
    args: [ 'setname', 'bull:U2VuZGluZyBXaGF0c0FwcCBNZXNzYWdlcw==' ]
  }
}
```

Bull version: 4.9.0
Redis Npm Version: 4.3.1
Redis Windows Client Version: 2.4.6

**Comment by manast** [comment]
Seems like your Redis instance does not support CLIENT setname command. You can try using redis-cli to confirm.
