### ISSUE TITLE
Error: Cannot set an undefined handler

### ISSUE THREAD

**Issue by yelnyafacee** [OptimalBits/bull#2476]
I got 2x javascript file `index.js` and `process.js`

I tried attaching `Event Listeners` to `process.js` like this:

```
// require("dotenv-safe").config(); // temp removed

// increase the max listeners to get rid of the warning below
// MaxListenersExceededWarning: Possible EventEmitter memory leak detected.
// 11 global:completed listeners added. Use emitter.setMaxListeners() to increase limit
const EventEmitter = require("events");
EventEmitter.defaultMaxListeners = 50;

// the processor to define/link
const { sendWhatsAppProcessor, uploadFileByIdProcessor } = require("../tasks/File/processor");

// the producer [ Queue ]
const { uploadFileByIdQueue, sendMessageQueue  } = require("."); // [ Import > From > Same > Directory ]

// import winston from "winston";

const winston = require('winston');

//
// const logger = require("any logger you want to use");


/*
|--------------------------------------------------------------------------
| Handler : Failure
|--------------------------------------------------------------------------
*/
const handleFailure = (job, err) => {

    // Job Retry Attempts > Exceeded
    if (job.attemptsMade >= job.opts.attempts) {

        // // Log : Error > Job Retry Attempts > Exceeded
        // logger.info(
        //     `Job failures above threshold in ${job.queue.name} for: ${JSON.stringify(
        //         job.data
        //     )}`,
        //     err
        // );

        console.log(`Job failures above threshold in ${job.queue.name} for: ${JSON.stringify(
            job.data
        )}`);

        // Remove > Job
        job.remove();

        return null;

    }

    // // Log : Error > Job Failed
    // logger.info(
    //     `Job in ${job.queue.name} failed for: ${JSON.stringify(job.data)} with ${
    //         err.message
    //     }. ${job.opts.attempts - job.attemptsMade} attempts left`
    // );

    console.log(`Job in ${job.queue.name} failed for: ${JSON.stringify(job.data)} with ${
        err.message
    }. ${job.opts.attempts - job.attemptsMade} attempts left`);

};

/*
|--------------------------------------------------------------------------
| Handler : Completed
|--------------------------------------------------------------------------
*/
const handleCompleted = job => {

    // // Log : Job Completed
    // logger.info(
    //     `Job in ${job.queue.name} completed for: ${JSON.stringify(job.data)}`
    // );

    console.log(`Job in ${job.queue.name} completed for: ${JSON.stringify(job.data)}`);

    // Remove > Job
    job.remove();

};

/*
|--------------------------------------------------------------------------
| Handler : Stalled
|--------------------------------------------------------------------------
*/
const handleStalled = job => {

    // // Log : Job Stalled
    // logger.info(
    //     `Job in ${job.queue.name} stalled for: ${JSON.stringify(job.data)}`
    // );

    console.log(`Job in ${job.queue.name} stalled for: ${JSON.stringify(job.data)}`);

};


/*
|--------------------------------------------------------------------------
| Object Array : Active Queue(s)
|--------------------------------------------------------------------------
*/
const activeQueues = [
    // {
    //     queue: uploadFileByIdQueue,
    //     processor: uploadFileByIdProcessor
    // },
    {
        queue: sendMessageQueue,
        processor: sendWhatsAppProcessor
    }
];


/*
|--------------------------------------------------------------------------
| Loop : Active Queue(s)
|--------------------------------------------------------------------------
*/
activeQueues.forEach( handler => {

    // Get > Queue
    const queue = handler.queue;

    // Get > Processor
    const processor = handler.processor;

    // Get > Fail Handler
    const failHandler = handler.failHandler || handleFailure;

    // Get > Completed Handler
    const completedHandler = handler.completedHandler || handleCompleted;

    // here are samples of listener events : "failed","completed","stalled", the other events will be ignored
    // Event Listeners Below:

    // On > Failed
    queue.on("failed", failHandler);

    // On > Completed
    queue.on("completed", completedHandler);

    // On > Stalled
    queue.on("stalled", handleStalled);

    // Run / Process > Queue
    queue.process(processor).then();// link the correspondant processor/worker

    // // Log : Queue Processing > Started
    // logger.info(`Processing ${queue.name}...`);

    console.log(`Processing ${queue.name}...`);

});
``` 

but I am getting the error:

```
C:\xampp\htdocs\nodejs-test>npm run process-queues

> nodejs-test@1.0.0 process-queues
> node ./app/queues/process.js

C:\xampp\htdocs\nodejs-test\node_modules\bull\lib\queue.js:670
    throw new Error('Cannot set an undefined handler');
    ^

Error: Cannot set an undefined handler
    at Queue.setHandler (C:\xampp\htdocs\nodejs-test\node_modules\bull\lib\queue.js:670:11)
    at Queue.process (C:\xampp\htdocs\nodejs-test\node_modules\bull\lib\queue.js:654:8)
    at C:\xampp\htdocs\nodejs-test\app\queues\process.js:150:11
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\xampp\htdocs\nodejs-test\app\queues\process.js:123:14)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

Node.js v17.8.0

```

The queue failed to process the job, so I moved the `Event Listener` code to `index.js` and it still trigger the same `Error` as above.

Here is my `index.js` file with `Event Listeners` added:

```
const Redis = require("ioredis");
const Queue = require("bull");


// Redis > Url
let redisUrl = null;

// Process ENV REDIS_URL > Exist
if (process.env.REDIS_URL) {

    // Set > redisUrl > to > Process ENV REDIS_URL
    redisUrl = process.env.REDIS_URL;
}

// Redis : Create > Client
const client = new Redis(redisUrl);

// Redis : Create > Subscriber
const subscriber = new Redis(redisUrl);

// Options
const opts = {

    createClient: function(type) {

        switch (type) {

            case "client":
                return client; // Return > Redis : Client

            case "subscriber":
                return subscriber; // Return > Redis : Subscriber

            default:
                return new Redis(redisUrl);

        }

    }
};

// Create > New > Queue [ UPLOAD_File_BY_ID ]
const uploadFileByIdQueue = new Queue("UPLOAD_File_BY_ID", opts);

// Create > New > Queue [ SEND_WHATSAPP_MESSAGE ]
const sendMessageQueue = new Queue("SEND_WHATSAPP_MESSAGE", opts);


/*
|--------------------------------------------------------------------------
| Handler : Failure
|--------------------------------------------------------------------------
*/
const handleFailure = (job, err) => {

    // Job Retry Attempts > Exceeded
    if (job.attemptsMade >= job.opts.attempts) {

        // // Log : Error > Job Retry Attempts > Exceeded
        // logger.info(
        //     `Job failures above threshold in ${job.queue.name} for: ${JSON.stringify(
        //         job.data
        //     )}`,
        //     err
        // );

        console.log(`Job failures above threshold in ${job.queue.name} for: ${JSON.stringify(
            job.data
        )}`);

        // Remove > Job
        job.remove();

        return null;

    }

    // // Log : Error > Job Failed
    // logger.info(
    //     `Job in ${job.queue.name} failed for: ${JSON.stringify(job.data)} with ${
    //         err.message
    //     }. ${job.opts.attempts - job.attemptsMade} attempts left`
    // );

    console.log(`Job in ${job.queue.name} failed for: ${JSON.stringify(job.data)} with ${
        err.message
    }. ${job.opts.attempts - job.attemptsMade} attempts left`);

};

/*
|--------------------------------------------------------------------------
| Handler : Completed
|--------------------------------------------------------------------------
*/
const handleCompleted = job => {

    // // Log : Job Completed
    // logger.info(
    //     `Job in ${job.queue.name} completed for: ${JSON.stringify(job.data)}`
    // );

    console.log(`Job in ${job.queue.name} completed for: ${JSON.stringify(job.data)}`);

    // Remove > Job
    job.remove();

};

/*
|--------------------------------------------------------------------------
| Handler : Stalled
|--------------------------------------------------------------------------
*/
const handleStalled = job => {

    // // Log : Job Stalled
    // logger.info(
    //     `Job in ${job.queue.name} stalled for: ${JSON.stringify(job.data)}`
    // );

    console.log(`Job in ${job.queue.name} stalled for: ${JSON.stringify(job.data)}`);

};


// here are samples of listener events : "failed","completed","stalled", the other events will be ignored
// Event Listeners Below:

// On > Failed
sendMessageQueue.on("failed", handleFailure);

// On > Completed
sendMessageQueue.on("completed", handleCompleted);

// On > Stalled
sendMessageQueue.on("stalled", handleStalled);



// Export > Queue
module.exports = {
    uploadFileByIdQueue,
    sendMessageQueue
};
```

I am using `OptimalBits/bull` version `^4.10.1`

Here is my `package.json` file:

```
{
  "name": "nodejs-test",
  "version": "1.0.0",
  "description": "Nodejs-test",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "process-queues": "node ./app/queues/process.js",
    "dev-queues": "nodemon ./app/queues/process.js",
    "debug-queues": "node --nolazy --inspect-brk=9242 ./app/queues/process.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^1.1.3",
    "bull": "^4.10.1",
    "cors": "^2.8.5",
    "dotenv": "^16.0.3",
    "dotenv-safe": "^8.2.0",
    "express": "^4.18.2",
    "ioredis": "^5.2.4",
    "lodash": "^4.17.21",
    "mysql": "^2.18.1",
    "mysql2": "^2.3.3",
    "qr-image": "^3.2.0",
    "sequelize": "^6.25.5",
    "uuid": "^9.0.0",
    "whatsapp-web.js": "^1.18.3",
    "winston": "^3.8.2"
  },
  "keywords": []
}
```

I cannot find any info on help on `Error: Cannot set an undefined handler`, cannot find anything related to it on Google search, I hope someone can enlighten me on what I did wrong  in the above code?

**Comment by manast** [comment]
Please isolate the issue in a small reproducible case, and we will look into it.

**Comment by manast** [comment]
Also, this may help you understand: https://github.com/OptimalBits/bull/blob/75e6775fc3720563aac9cd9a07d1722dfbdfa177/lib/queue.js#L668
