### ISSUE TITLE
Job failed with `TimeoutError: operation timed out`

### ISSUE THREAD

**Issue by andrewtamura** [OptimalBits/bull#259]
We're seeing jobs occasionally fail with the following stack trace.

```
TimeoutError: operation timed out
    at afterTimeout (/var/app/current/node_modules/bull/node_modules/bluebird/js/main/timers.js:16:15)
    at timeoutTimeout (/var/app/current/node_modules/bull/node_modules/bluebird/js/main/timers.js:59:9)
    at Timer.listOnTimeout (timers.js:92:15)
```

I'm unable to create reliable repo steps, but I'll report back when I do. It appears that this exception is more common on jobs that use the delay feature. We're using bull version 0.7.2.

**Comment by shekyan** [comment]
I got this error locally:
```
Warning: a promise was created in a handler but was not returned from it
    at Job.remove (/Users/sergey/mxmx/contacts/node_modules/bull/lib/job.js:309:28)
    at Queue.<anonymous> (/Users/sergey/mxmx/contacts/src/jobqueue.js:18:7)
    at emitTwo (events.js:87:13)
    at Queue.emit (events.js:172:7)
    at /Users/sergey/mxmx/contacts/node_modules/bull/lib/queue.js:605:13
    at RedisClient.return_reply (/Users/sergey/mxmx/contacts/node_modules/redis/index.js:664:25)
    at HiredisReplyParser.reply_parser.send_reply (/Users/sergey/mxmx/contacts/node_modules/redis/index.js:332:14)
    at HiredisReplyParser.execute (/Users/sergey/mxmx/contacts/node_modules/redis/lib/parsers/hiredis.js:30:18)
    at Socket.<anonymous> (/Users/sergey/mxmx/contacts/node_modules/redis/index.js:131:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
From previous event:
    at handleCompleted (/Users/sergey/mxmx/contacts/node_modules/bull/lib/queue.js:604:38)
    at /Users/sergey/mxmx/contacts/src/jobs/sync/sync.js:85:10
    at /Users/sergey/mxmx/contacts/node_modules/synchronize/sync.js:278:7
From previous event:
    at Queue.processJob (/Users/sergey/mxmx/contacts/node_modules/bull/lib/queue.js:632:6)
    at /Users/sergey/mxmx/contacts/node_modules/bull/lib/queue.js:577:20
From previous event:
    at Queue.takeLockAndProcessJob (/Users/sergey/mxmx/contacts/node_modules/bull/lib/queue.js:575:35)
From previous event:
    at Queue.processJobs (/Users/sergey/mxmx/contacts/node_modules/bull/lib/queue.js:564:6)
    at RedisClient.return_reply (/Users/sergey/mxmx/contacts/node_modules/redis/index.js:664:25)
    at HiredisReplyParser.reply_parser.send_reply (/Users/sergey/mxmx/contacts/node_modules/redis/index.js:332:14)
    at HiredisReplyParser.execute (/Users/sergey/mxmx/contacts/node_modules/redis/lib/parsers/hiredis.js:30:18)
    at Socket.<anonymous> (/Users/sergey/mxmx/contacts/node_modules/redis/index.js:131:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
From previous event:
    at Queue.processJobs (/Users/sergey/mxmx/contacts/node_modules/bull/lib/queue.js:566:6)
    at Queue.run (/Users/sergey/mxmx/contacts/node_modules/bull/lib/queue.js:441:24)
    at Queue.process (/Users/sergey/mxmx/contacts/node_modules/bull/lib/queue.js:231:15)
    at Object.<anonymous> (/Users/sergey/mxmx/contacts/src/jobqueue.js:34:7)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/sergey/mxmx/contacts/app.js:38:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

Steps to reproduce are to create a MM with an invalid email like `rov...@gmail.com` which passes our validation but is rejected by GMail.

**Comment by NoiLe** [comment]
hi @andrewtamura , I've encountered the same issue, did you find out the root cause?

**Comment by bradvogel** [comment]
I believe this issue is just caused by a failure to connect to Redis.
