### ISSUE TITLE
Job fails with `Error: INCR can't be processed. The connection has already been closed`

### ISSUE THREAD

**Issue by andrewtamura** [OptimalBits/bull#260]
Bull version 0.7.2.

```
Error: INCR can't be processed. The connection has already been closed.
    at RedisClient.send_command (/var/app/current/node_modules/redis/index.js:788:23)
    at RedisClient.(anonymous function).RedisClient.(anonymous function) (/var/app/current/node_modules/redis/index.js:966:25)
    at RedisClient.tryCatcher (/var/app/current/node_modules/bull/node_modules/bluebird/js/release/util.js:16:23)
    at RedisClient.ret [as incrAsync] (eval at <anonymous> (/var/app/current/node_modules/bull/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at Queue.add (/var/app/current/node_modules/bull/lib/queue.js:280:23)
```

**Comment by bradvogel** [comment]
I bet this can be closed now
