### ISSUE TITLE
cannot add a job to another queue while handler process completed in current queue

### ISSUE THREAD

**Issue by yunyu950908** [OptimalBits/bull#2606]
## Description

cannot add a job to another queue while handler completed in current queue

## Bull version

```
"bull": "^4.10.4"
```

## Additional information

```
[
{
command: {
args: [
--[[
  Adds a job to the queue by doing the following:
    - Increases the job counter if needed.
    - Creates a new job key with the job data.

    - if delayed:
      - computes timestamp.
      - adds to delayed zset.
      - Emits a global event 'delayed' if the job is delayed.
    - if not delayed
      - Adds the jobId to the wait/paused list in one of three ways:
         - LIFO
         - FIFO
         - prioritized.
      - Adds the job to the "added" list so that workers gets notified.

    Input:
      KEYS[1] 'wait',
      KEYS[2] 'paused'
      KEYS[3] 'meta-paused'
      KEYS[4] 'id'
      KEYS[5] 'delayed'
      KEYS[6] 'priority'

      ARGV[1]  key prefix,
      ARGV[2]  custom id (will not generate one automatically)
      ARGV[3]  name
      ARGV[4]  data (json stringified job data)
      ARGV[5]  opts (json stringified job opts)
      ARGV[6]  timestamp
      ARGV[7]  delay
      ARGV[8]  delayedTimestamp
      ARGV[9]  priority
      ARGV[10] LIFO
      ARGV[11] token
]]
local jobId
local jobIdKey
local rcall = redis.call

local jobCounter = rcall("INCR", KEYS[4])

if ARGV[2] == "" then
  jobId = jobCounter
  jobIdKey = ARGV[1] .. jobId
else
  jobId = ARGV[2]
  jobIdKey = ARGV[1] .. jobId
  if rcall("EXISTS", jobIdKey) == 1 then
    return jobId .. "" -- convert to string
  end
end

-- Store the job.
rcall("HMSET", jobIdKey, "name", ARGV[3], "data", ARGV[4], "opts", ARGV[5], "timestamp", ARGV[6], "delay", ARGV[7], "priority", ARGV[9])

-- Check if job is delayed
local delayedTimestamp = tonumber(ARGV[8])
if(delayedTimestamp ~= 0) then
  local timestamp = delayedTimestamp * 0x1000 + bit.band(jobCounter, 0xfff)
  rcall("ZADD", KEYS[5], timestamp, jobId)
  rcall("PUBLISH", KEYS[5], delayedTimestamp)
else
  local target

  -- Whe check for the meta-paused key to decide if we are paused or not
  -- (since an empty list and !EXISTS are not really the same)
  local paused
  if rcall("EXISTS", KEYS[3]) ~= 1 then
    target = KEYS[1]
    paused = false
  else
    target = KEYS[2]
    paused = true
  end

  -- Standard or priority add
  local priority = tonumber(ARGV[9])
  if priority == 0 then
      -- LIFO or FIFO
    rcall(ARGV[10], target, jobId)
  else
    -- Priority add
    rcall("ZADD", KEYS[6], priority, jobId)
    local count = rcall("ZCOUNT", KEYS[6], 0, priority)

    local len = rcall("LLEN", target)
    local id = rcall("LINDEX", target, len - (count-1))
    if id then
      rcall("LINSERT", target, "BEFORE", id, jobId)
    else
      rcall("RPUSH", target, jobId)
    end

  end

  -- Emit waiting event (wait..ing@token)
  rcall("PUBLISH", KEYS[1] .. "ing@" .. ARGV[11], jobId)
end

return jobId .. "" -- convert to string
, 
6, 
{dcmj_queue}:dm2:wait, 
{dcmj_queue}:dm2:paused, 
{dcmj_queue}:dm2:meta-paused, 
{dcmj_queue}:dm2:id, 
{dcmj_queue}:dm2:delayed, 
{dcmj_queue}:dm2:priority, 
{dcmj_queue}:dm2:, 
, 
__default__, 
[Filtered], 
{"removeOnComplete":{"count":100},"removeOnFail":{"count":100},"attempts":1,"delay":0,"timestamp":1685113160475}, 
1685113160475, 
0, 
0, 
0, 
LPUSH, 
30af8582-8705-4604-838a-f6c305a99e21
], 
name: eval
}, 
message: ERR 'EVAL' inside MULTI is not allowed, 
name: ReplyError, 
stack: 
ReplyError: ERR 'EVAL' inside MULTI is not allowed
    at parseError (/usr/src/app/node_modules/.pnpm/registry.npmmirror.com+redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/.pnpm/registry.npmmirror.com+redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)
}
]
```

**Comment by manast** [comment]
You need to provide some code that reproduces the issue you are having.

**Comment by yunyu950908** [comment]
here @manast 
```
import Bull from 'bull'
import { setTimeout } from 'timers/promises'

const REDIS_URL = process.env.REDIS_URL as string

const createQueue = (name: string) =>
  new Bull(name, REDIS_URL, {
    prefix: '{test_dcmj_queue}',
  })

const q1 = createQueue('q1')

const q2 = createQueue('q2')

q1.add({ a: new Date() }, { repeat: { every: 1000 * 2 } })

q1.process(async (job) => {
  await setTimeout(1000)
  console.log(job.queue.name, job.data)
  const datas = Array.from({ length: 5 }, () => ({ data: new Date() }))
  console.log(datas)
  await q2.addBulk(datas)
})

q2.process(async (job) => {
  console.log(job.queue.name)
  console.log(JSON.stringify(job.data))
})

```

here is the printed logs 
```
q1 { a: '2023-05-27T12:17:58.285Z' }
[
  { data: 2023-05-27T12:23:36.433Z },
  { data: 2023-05-27T12:23:36.433Z },
  { data: 2023-05-27T12:23:36.433Z },
  { data: 2023-05-27T12:23:36.433Z },
  { data: 2023-05-27T12:23:36.433Z }
]
q1 { a: '2023-05-27T12:19:27.089Z' }
[
  { data: 2023-05-27T12:23:42.705Z },
  { data: 2023-05-27T12:23:42.705Z },
  { data: 2023-05-27T12:23:42.705Z },
  { data: 2023-05-27T12:23:42.705Z },
  { data: 2023-05-27T12:23:42.705Z }
]
```

note: this works on a standalone redis. But stucked with a redis cluster

**Comment by manast** [comment]
https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#redis-cluster

**Comment by yunyu950908** [comment]
here is the redis info

```
# Server
redis_version:5.0.5
tcp_port:6379
uptime_in_seconds:93000390
uptime_in_days:1076
hz:10
lru_clock:7468814

# Clients
connected_clients:8
blocked_clients:12

# Memory
used_memory:96393340080
used_memory_human:89.77G
used_memory_rss:103707144192
used_memory_rss_human:96.58G
used_memory_peak:133249968688
used_memory_peak_human:124.10G
used_memory_overhead:930535318
used_memory_overhead_human:887.43M
used_memory_startup:84502600
used_memory_startup_human:80.59M
used_memory_dataset:95462804762
used_memory_dataset_human:88.91G
used_memory_lua:689152
used_memory_lua_human:673.00K
maxmemory:137438953472
maxmemory_human:128.00G
maxmemory_policy:volatile-lru
mem_fragmentation_ratio:1.08
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Stats
total_connections_received:3001132999
total_commands_processed:237426038009
instantaneous_ops_per_sec:2383
total_net_input_bytes:36740250207758
total_net_output_bytes:168932003213631
instantaneous_input_kbps:302
instantaneous_output_kbps:2054
rejected_connections:0
sync_full:8
sync_partial_ok:1
sync_partial_err:1
expired_keys:13632122171
evicted_keys:38396425
keyspace_hits:144248310039
keyspace_misses:150523162750
pubsub_channels:929
pubsub_patterns:0
latest_fork_usec:575334
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:1
master_replid:a313451d080226ec0fa022dd3737f8f5392b05f1
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:1769723743326
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:33554432
repl_backlog_first_byte_offset:1769690188895
repl_backlog_histlen:33554432

# CPU
used_cpu_sys:3584388.46
used_cpu_user:6594577.67
used_cpu_sys_children:38523.37
used_cpu_user_children:405308.55

# Cluster
cluster_enabled:0
databases:256
nodecount:8

# Keyspace
db4:keys=526,expires=521,avg_ttl=86031130212
db0:keys=5899150,expires=2849736,avg_ttl=97308660094
```

**Comment by yunyu950908** [comment]
I dont understand, sir.

I have followed `However, it is still possible to use a cluster environment by using the proper bull prefix option as a cluster "hash tag".` and `If you use several queues in the same cluster, you should use different prefixes so that the queues are evenly placed in the cluster nodes.`

q1's prefix is `{test_dcmj_queue_q1}`
q2's prefix is `{test_dcmj_queue_q2}`

but it still doesn't work.

**Comment by deemstone** [comment]
this Error produced by Aliyun redis proxy, document link : https://help.aliyun.com/zh/redis/support/usage-of-lua-scripts?#section-8f7-qgv-dlv
