### ISSUE TITLE
Timeout during queue.close() leads to unhandled rejection / crash

### ISSUE THREAD

**Issue by jlukanta** [OptimalBits/bull#283]
I tested against the newest version of master, but I believe the problem has happened since a while ago.

I made the following change in `Queue#disconnect` to guarantee a timeout:

```
  function endClients(){
    var timeoutMsg = 'Timed out while waiting for redis clients to close';

    return new Promise(function(resolve) {
      // var triggerEvent = _.after(3, resolve);
      // _this.client.end(true);
      // _this.bclient.end(true);
      // _this.eclient.end(true);
      // _this.client.stream.once('close', triggerEvent);
      // _this.bclient.stream.once('close', triggerEvent);
      // _this.eclient.stream.once('close', triggerEvent);
    }).timeout(CLIENT_CLOSE_TIMEOUT_MS, timeoutMsg);
  }
```

This is my test case. The idea is to create a queue, close it, wait for timeout, and catch any error.

```
var Promise = require('bluebird');
var Queue = require('bull');

process.on('unhandledRejection', function(err, promise) {
  console.info('In unhandledRejection');
  throw err;
});

var queue = new Queue('test', 6379, '127.0.0.1');
queue.once('ready', function() {
  Promise.resolve().then(function() {
    queue.process(function(job, done) {
      console.info('Processing job : ' + job.jobId);
      done();
    });
  }).then(function() {
    return queue.close().then(function() {
      console.info('Closing queue OK');
    }).catch(function(err) {
      console.error('Error while closing queue - ' + err);
    });
  });
});
```

This program should only print the error message 'Error while closing queue - .....'. However, in this case, the `unhandledRejection` handler will also be called because `Queue#process` catches and rethrows any error from `queue.run()`.  The error was caught because `queue.run()` calls `processStalledJobs` and `processJobs`, which leads to multiple executions of the `closed` promise that was set in `Queue#close`.

This is the output:

```
Resolving closed from processJobs
Returning closed from processStalledJobs
Error while closing queue - TimeoutError: Timed out while waiting for redis clients to close
In process.run.catch about to throw err : TimeoutError: Timed out while waiting for redis clients to close
In unhandledRejection

/sanitized/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^
TimeoutError: Timed out while waiting for redis clients to close
    at afterTimeout (/sanitized/node_modules/bluebird/js/release/timers.js:48:15)
    at timeoutTimeout [as _onTimeout] (/sanitized/node_modules/bluebird/js/release/timers.js:75:13)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by manast** [comment]
Good catch, I will see what I can do to fix it.
