### ISSUE TITLE
Script attempted to access unexisting global variable 'bit'

### ISSUE THREAD

**Issue by aaronroberson** [OptimalBits/bull#294]
Bull is throwing an error when attempting to add a job to the queue. I believe the error is thrown on the following line:

https://github.com/OptimalBits/bull/blob/c61e3ff88277f33ebec30c060588f85b31ff49c9/lib/scripts.js#L90

Here is the stacktrace:
```
Unhandled rejection Error: ERR Error running script (call to f_1f46a25dd9f50b1331d5c86b90ba4dce1e15cd8f): @enable_strict_lua:14: user_script:3: Script attempted to access unexisting global variable 'bit' 
    at JavascriptReplyParser.parseResult (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/redis-parser/lib/javascript.js:90:16)
    at JavascriptReplyParser.tryParsing (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/redis-parser/lib/javascript.js:117:21)
    at JavascriptReplyParser.run (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/redis-parser/lib/javascript.js:131:22)
    at JavascriptReplyParser.execute (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/bull/node_modules/redis/index.js:223:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

I had opened a ticket with node_redis, believing it was a redis error because redis appears to be gobbling it up. Please also see https://github.com/NodeRedis/node_redis/issues/1058#issuecomment-218183022

**Comment by manast** [comment]
hmm, can you try with a version of redis 3.0.0+ ?
