### ISSUE TITLE
bull 1.0.0-rc1, error with redis 3.2?

### ISSUE THREAD

**Issue by cvlmtg** [OptimalBits/bull#295]
I started having problems with bull today and I suspect the cause may be the new redis 3.2.0 (installed with homebrew on my osx 10.11).

as soon as a job is completed and the callback called, this is what happens:

```
{ Error: ERR Error running script (call to f_7bae1666c6fc0e1b7f73920dd0fe76cdfbf9563b): @user_script:3: @user_script: 3: Lua redis() command arguments must be strings or integers
at Error (native)
at HiredisReplyParser.parseData (/Users/matteo/dev/liquid_server/node_modules/redis-parser/lib/hiredis.js:13:28)
at HiredisReplyParser.execute (/Users/matteo/dev/liquid_server/node_modules/redis-parser/lib/hiredis.js:24:22)
From previous event:
at /Users/matteo/dev/liquid_server/node_modules/bull/lib/scripts.js:28:32
etc...
```

the script should be the one created inside ```lib/scripts.js``` in the ```addJob``` function.

I tried with bull 0.7.2 and I got these warnings:

```
node_redis: Deprecated: The HMSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
```

**Comment by cvlmtg** [comment]
sorry, the culprit isn't ```addJob``` but ```moveToCompleted```. If I modify

```
    if(!_.isUndefined(job.returnvalue)){
      args.push(JSON.stringify(job.returnvalue));
    }
```

to

```
    if(!_.isUndefined(job.returnvalue)){
      args.push(JSON.stringify(job.returnvalue));
    } else {
      args.push(null);
    }
```

I get these warnings:

```
node_redis: Deprecated: The EVALSHA command contains a "null" argument.
This is converted to a "null" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
```

but at least the program doesn't crash anymore. I've no idea how to fix the problem and what other value should be placed instead of null when job.returnValue is undefined.

**Comment by aputinski** [comment]
I'm having the same issue running Redis `3.2.0`
```javascript
// Avoid the error by passing a result
done(null, true)
```
