### ISSUE TITLE
Cleaning Unhandled rejection Error

### ISSUE THREAD

**Issue by Bersam** [OptimalBits/bull#333]
I have multiple job queues, got big as 10K items in each. Also I have a cron job that at first pause a queue then it tries to clean completed jobs and resume queue again, but I get this error randomly, here's part of code: [https://gist.github.com/Bersam/c46148decf0acf4b8544a66f13f11bcd](clean.js)

```
 Unhandled rejection Error: Could not get lock for job: 3. Cannot remove job.
     at /var/www/instafollow/node_modules/bull/lib/job.js:292:13
     at tryCatcher (/var/www/instafollow/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/var/www/instafollow/node_modules/bluebird/js/release/promise.js:504:31)
     at Promise._settlePromise (/var/www/instafollow/node_modules/bluebird/js/release/promise.js:561:18)
     at Promise._settlePromise0 (/var/www/instafollow/node_modules/bluebird/js/release/promise.js:606:10)
     at Promise._settlePromises (/var/www/instafollow/node_modules/bluebird/js/release/promise.js:685:18)
     at Promise._fulfill (/var/www/instafollow/node_modules/bluebird/js/release/promise.js:630:18)
     at Promise._resolveCallback (/var/www/instafollow/node_modules/bluebird/js/release/promise.js:425:57)
     at Promise._settlePromiseFromHandler (/var/www/instafollow/node_modules/bluebird/js/release/promise.js:516:17)
     at Promise._settlePromise (/var/www/instafollow/node_modules/bluebird/js/release/promise.js:561:18)
     at Promise._settlePromise0 (/var/www/instafollow/node_modules/bluebird/js/release/promise.js:606:10)
     at Promise._settlePromises (/var/www/instafollow/node_modules/bluebird/js/release/promise.js:685:18)
     at Promise._fulfill (/var/www/instafollow/node_modules/bluebird/js/release/promise.js:630:18)
     at Command.callback (/var/www/instafollow/node_modules/bluebird/js/release/nodeback.js:42:21)
     at normal_reply (/var/www/instafollow/node_modules/redis/index.js:714:21)
     at RedisClient.return_reply (/var/www/instafollow/node_modules/redis/index.js:816:9)
     at JavascriptRedisParser.Parser.returnReply (/var/www/instafollow/node_modules/redis/index.js:188:18)
     at JavascriptRedisParser.execute (/var/www/instafollow/node_modules/redis-parser/lib/parser.js:408:12)
     at Socket.<anonymous> (/var/www/instafollow/node_modules/redis/index.js:267:27)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at readableAddChunk (_stream_readable.js:172:18)
```

**Comment by igorissen** [comment]
Same issue here in production `node v5.9.1` (should upgrade to latest node version) and `"bull": "^1.0.0"`.

```
Error: Could not get lock for job: 578. Cannot remove job. File "/home/ubuntu/project/node_modules/bull/lib/job.js", line 292, in <unknown> throw new Error('Could not get lock for job: ' + job.jobId + '. Cannot remove job.'); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/util.js", line 16, in tryCatcher return target.apply(this, arguments); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/promise.js", line 504, in Promise._settlePromiseFromHandler x = tryCatch(handler).call(receiver, value); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/promise.js", line 561, in Promise._settlePromise this._settlePromiseFromHandler(handler, receiver, value, promise); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/promise.js", line 606, in Promise._settlePromise0 this._settlePromise(promise, handler, receiver, value); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/promise.js", line 685, in Promise._settlePromises this._settlePromise0(this._fulfillmentHandler0, value, bitField); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/promise.js", line 630, in Promise._fulfill this._settlePromises(); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/promise.js", line 425, in Promise._resolveCallback if (!(maybePromise instanceof Promise)) return this._fulfill(value); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/promise.js", line 516, in Promise._settlePromiseFromHandler promise._resolveCallback(x); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/promise.js", line 561, in Promise._settlePromise this._settlePromiseFromHandler(handler, receiver, value, promise); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/promise.js", line 606, in Promise._settlePromise0 this._settlePromise(promise, handler, receiver, value); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/promise.js", line 685, in Promise._settlePromises this._settlePromise0(this._fulfillmentHandler0, value, bitField); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/promise.js", line 630, in Promise._fulfill this._settlePromises(); File "/home/ubuntu/project/node_modules/bull/node_modules/bluebird/js/release/nodeback.js", line 42, in Command.callback promise._fulfill(value); File "/home/ubuntu/project/node_modules/redis/index.js", line 714, in normal_reply command_obj.callback(null, reply); File "/home/ubuntu/serist/node_modules/redis/index.js", line 816, in RedisClient.return_reply normal_reply(this, reply); File "/home/ubuntu/project/node_modules/redis/index.js", line 188, in JavascriptRedisParser.Parser.returnReply self.return_reply(data); File "/home/ubuntu/project/node_modules/redis-parser/lib/parser.js", line 413, in JavascriptRedisParser.execute this.returnReply(response) // Strings + // Integers : // Bulk strings $ // Arrays * File "/home/ubuntu/project/node_modules/redis/index.js", line 267, in Socket.<anonymous> self.reply_parser.execute(buffer_from_socket); File "events.js", line 90, in emitOne File "events.js", line 182, in Socket.emit File "_stream_readable.js", line 153, in readableAddChunk
```

**Comment by manast** [comment]
We believe this issue has been resolved. Please reopen if not.
