### ISSUE TITLE
-OOM command not allowed when used memory > 'maxmemory'. 

### ISSUE THREAD

**Issue by n3trino** [OptimalBits/bull#416]
1|wover    | ReplyError: ERR Error running script (call to f_bed0f540aaab40cb5b63c076c00c75504e27424b): @user_script:1: @user_script: 1: -OOM command not allowed when used memory > 'maxmemory'.   
1|wover    |     at JavascriptReplyParser.returnError (/home/apiUser/wover-backend/node_modules/ioredis/lib/redis/parser.js:25:25)
1|wover    |     at JavascriptReplyParser.run (/home/apiUser/wover-backend/node_modules/ioredis/node_modules/redis-parser/lib/javascript.js:135:18)
1|wover    |     at JavascriptReplyParser.execute (/home/apiUser/wover-backend/node_modules/ioredis/node_modules/redis-parser/lib/javascript.js:112:10)
1|wover    |     at Socket.<anonymous> (/home/apiUser/wover-backend/node_modules/ioredis/lib/redis/event_handler.js:107:22)
1|wover    |     at emitOne (events.js:96:13)
1|wover    |     at Socket.emit (events.js:188:7)
1|wover    |     at readableAddChunk (_stream_readable.js:176:18)
1|wover    |     at Socket.Readable.push (_stream_readable.js:134:10)
1|wover    |     at TCP.onread (net.js:548:20)

**Comment by manast** [comment]
I have no idea what this can be. But it seems like a limitation with redis. We should then document that maxmemory can not be used with bull.

**Comment by jsarenik** [comment]
You may need to check out the `removeOnComplete` option. See [the documentation](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd) for more info.

If you implement your own `.on('failed', ...` then also `removeOnFail` should be set to `1`.

Otherwise redis is being filled with all the old jobs in the completed state.

**Comment by jsarenik** [comment]
@manast The default `maxmemory-policy` is `noeviction` which just returns an error on write operations. That may be what @n3trino sees.

@n3trino could you please try to run redis with `maxmemory-policy allkeys-lru`? Of course it is not the solution, I just want to check if that error is caused by errors from redis because the memory is full and `noeviction` is set. Thank you.

**Comment by rinogo** [comment]
Our production ElastiCache has run out of memory due to running with Bull and Redis defaults. It sounds like we either need to remove completed and failed jobs or change our configuration to use a non-default `maxmemory-policy` (probably `allkeys-lru`).

The docs should really be improved regarding all of this - seems like an important bit of prerequisite/setup information for Bull.

**Comment by lakshay2711** [comment]
I am also facing similar issues it seems below bull configuration does not have any effect and still keys are growing in aws redis:

bull: {
      defaultQueueOptions: {
        redis: {
          port: xxx,
          host: xxx,
          password: xxx,
          tls: {}
        },
        defaultJobOptions: {
          removeOnComplete: 1000,
          removeOnFail: 1000
        },
      }
    }

Can anyone please let me know how to resolve this issue ?

**Comment by lakshay2711** [comment]
@manast Sorry I am new to this, can you please let me know when exactly a new key would be created in aws redis, is it when we add a new job to the queue ? If yes, then for each and every request will it would be adding a key to the redis ?
