### ISSUE TITLE
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.

### ISSUE THREAD

**Issue by jcald1** [OptimalBits/bull#436]
In bull v 2.1.0 , I'm getting the following strict mode error.  It looks like some functions are declared in an if/else block in job.js starting at line 364.

```
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/apps/das/src/DynamicNotificationService/node_modules/bull/lib/queue.js:9:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/apps/das/src/DynamicNotificationService/node_modules/bull/index.js:1:80)
    at Module._compile (module.js:460:26)
/usr/apps/das/src/DynamicNotificationService/node_modules/bull/lib/job.js:364
        function onCompleted(job){
        ^^^^^^^^
```

**Comment by manast** [comment]
Interesting. I wonder why the unit tests are going through.

**Comment by jcald1** [comment]
It may have something to do with the Node version. I got the error with Node v0.12.7 on Red Hat 6.8, but not on Node 6.8 on Ubuntu 14.04.5.

**Comment by PyroSA** [comment]
Same issue tripped my staging server.

Bull 1.0.0 works on node 0.12.15.
Bull 1.1.0 and upwards give the strict mode error.

**Comment by manast** [comment]
0.12 is not supported anymore. Nevertheless, I think this issue is not present on latest 2.1.1 version either.

**Comment by PyroSA** [comment]
Thanks. It's a low priority project, but will upgrade bull when I look at it again.
