### ISSUE TITLE
Unable to renew nonexisting lock on job fail

### ISSUE THREAD

**Issue by raminious** [OptimalBits/bull#441]
Same as #413 I'm getting this error

```
/Development/node/bull-test/node_modules/bull/lib/scripts.js:289
      throw new Error('Unable to renew nonexisting lock');
      ^

Error: Unable to renew nonexisting lock
    at Object.takeLock (/Development/node/bull-test/node_modules/bull/lib/scripts.js:289:13)
    at Job.takeLock (/Development/node/bull-test/node_modules/bull/lib/job.js:128:18)
    at lockRenewer (/Development/node/bull-test/node_modules/bull/lib/queue.js:644:16)
    at Timeout.<anonymous> (/Development/node/bull-test/node_modules/bull/lib/timer-manager.js:80:5)
    at Timeout.ontimeout (timers.js:344:34)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

My sample code that reproduces this error:

```js
const Queue = require('bull')
const co = require('co')

const appQueue = new Queue('app-test')

const delay = function(time) {
  return new Promise(resolve => {
    return setTimeout(resolve, time)
  })
}

appQueue.process(200, co.wrap(function* (job) {
  console.log('[ * ] Job ' + job.jobId + ' started.')
  yield delay(20000)
  console.log('[ * ] Job ' + job.jobId + ' is done.')
  return { name: job.data.name, status: 'OK' }
}))

appQueue
.on('completed', function (job, result) {
  console.log('Job Completed ', result)
})
.on('failed', function (job, result) {
  console.log('Job Failed ', result)
})

/*
* create some jobs
*/
for (let i = 1; i <= 1000; i++) {
  appQueue.add({ name: 'Job #' + i }, {
    attempts: 1,
    timeout: 5 * 1000,
    removeOnComplete: false
  })
}
```

QA:
use cluster: no
node version: v6.6.0
bull version: 2.1.0 (latest)
redis version: redis-cli 3.2.3
os: mac osx el capitan

![bull](https://cloud.githubusercontent.com/assets/334716/22362211/3d685e5e-e476-11e6-9b8f-37f7b836b76f.gif)

**Comment by raminious** [comment]
@manast I'm so sorry for direct ping, but can you give an estimate when fix coming ?

**Comment by manast** [comment]
@raminious let me check that code, see if I can reproduce it.

**Comment by manast** [comment]
I could reproduce the issue. Although I do not know yet the cause, at least I catch the error now so that the queue can continue working. I release a patch version 2.1.1. I will try to find the underlying cause in the following days.

**Comment by raminious** [comment]
@manast Thanks for 2.1.1 release, I keep this issue open since you find the underlying cause. 👍

**Comment by raminious** [comment]
@manast any good news buddy ?
