### ISSUE TITLE
Error processing job: Error: Missing Job 2649944 when trying to move from active to undefined

### ISSUE THREAD

**Issue by jahraphael** [OptimalBits/bull#469]
Hi there,

I'm running Bull across about 30 containers each running a single queue consumer process with `concurrency` = 2, and I seem to encounter an occasional problem where my logs start to get spammed with the error message below.

It seems like a lot of job processing still proceeds, but these errors continue for some period of time (hours?), then things will subside again.

Error message:

```
Error processing job: Error: Missing Job 2649944 when trying to move from active to undefined
    at node_modules/bull/lib/scripts.js:193:19
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:580:21)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (node_modules/bluebird/js/release/promise.js:636:18)
    at Command.callback (node_modules/bluebird/js/release/nodeback.js:42:21)
    at normal_reply (node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (node_modules/redis/index.js:819:9)
    at JavascriptRedisParser.returnReply (node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (node_modules/redis-parser/lib/parser.js:560:12)
```

About my environment:

Node version: 6.9.5
Bull version: 2.2.3 (I noticed 2.2.5 is released so am upgrading to that to test again)
Redis version: 3.2.4

What additional useful information could I provide to help narrow this down?

**Comment by jahraphael** [comment]
I just noticed a bug where our main control instance was still on a very old version of Bull, so I am going to close this issue for now while I re-test after fixing this. If it occurs again I will raise the issue again.

**Comment by manast** [comment]
Please let me know if the issue happens again with the newer bull worker.
