### ISSUE TITLE
MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk.

### ISSUE THREAD

**Issue by imjustd** [OptimalBits/bull#540]
When I deploy my code I get this error:

```
command: 
   { name: 'brpoplpush',
     args: 
      [ 'bull:Image Upload Queue:wait',
        'bull:Image Upload Queue:active',
        '2' ] } }
Error processing job: { ReplyError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
    at JavascriptReplyParser.returnError (/var/app/current/node_modules/ioredis/lib/redis/parser.js:25:25)
    at JavascriptReplyParser.run (/var/app/current/node_modules/redis-parser/lib/javascript.js:135:18)
    at JavascriptReplyParser.execute (/var/app/current/node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (/var/app/current/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
From previous event:
    at Command.initPromise (/var/app/current/node_modules/ioredis/lib/command.js:63:18)
    at new Command (/var/app/current/node_modules/ioredis/lib/command.js:51:8)
    at Redis.brpoplpush (/var/app/current/node_modules/ioredis/lib/commander.js:131:29)
    at Queue.moveJob (/var/app/current/node_modules/bull/lib/queue.js:809:25)
    at Queue.getNextJob (/var/app/current/node_modules/bull/lib/queue.js:763:17)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Promise.then (/var/app/current/node_modules/sequelize/lib/promise.js:21:17)
    at /var/app/current/node_modules/bull/lib/queue.js:647:10
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  name: 'ReplyError',
  message: 'MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.',
  command: 
```

I have no idea how to fix this, I've tried the solution offered here http://stackoverflow.com/questions/19581059/misconf-redis-is-configured-to-save-rdb-snapshots
without any success. Any suggestions what could be the problem?

**Comment by manast** [comment]
seems like the redis instance does not have rights or there is no space left to write to disk. So the alternative would be to either disable snapshots (and persistence), or make space in the storage for redis.
I will close this issue since it is not Bull related.
