### ISSUE TITLE
Bull 3.0.0-rc1 issue with promises

### ISSUE THREAD

**Issue by Climax777** [OptimalBits/bull#546]
I'm running a basic setup here with ioredis, getting the following error.
```
Error: cannot enable cancellation after promises are in use
    at Function.Promise.config (/home/pieter/Programming/node/camera-viewer/node_modules/bluebird/js/release/debuggability.js:269:19)
    at Object.<anonymous> (/home/pieter/Programming/node/camera-viewer/node_modules/bull/lib/queue.js:22:9)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/pieter/Programming/node/camera-viewer/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (/home/pieter/Programming/node/camera-viewer/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pieter/Programming/node/camera-viewer/server/api/site/site.jobs.js:36:13)
    at Module._compile (module.js:571:32)
    at loader (/home/pieter/Programming/node/camera-viewer/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/pieter/Programming/node/camera-viewer/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (/home/pieter/Programming/node/camera-viewer/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/pieter/Programming/node/camera-viewer/server/config/bull.js:58:4
    at Array.forEach (native)
    at /home/pieter/Programming/node/camera-viewer/server/config/bull.js:56:9
    at f (/home/pieter/Programming/node/camera-viewer/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/pieter/Programming/node/camera-viewer/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:191:7)
    at Glob._finish (/home/pieter/Programming/node/camera-viewer/node_modules/glob/glob.js:197:8)
    at done (/home/pieter/Programming/node/camera-viewer/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/home/pieter/Programming/node/camera-viewer/node_modules/glob/glob.js:637:12)
    at /home/pieter/Programming/node/camera-viewer/node_modules/glob/glob.js:626:10
    at RES (/home/pieter/Programming/node/camera-viewer/node_modules/inflight/inflight.js:31:16)
    at f (/home/pieter/Programming/node/camera-viewer/node_modules/once/once.js:25:25)
    at lstatcb_ (/home/pieter/Programming/node/camera-viewer/node_modules/glob/glob.js:519:7)
    at RES (/home/pieter/Programming/node/camera-viewer/node_modules/inflight/inflight.js:31:16)
    at f (/home/pieter/Programming/node/camera-viewer/node_modules/once/once.js:25:25)
    at FSReqWrap.oncomplete (fs.js:114:15)
```

I can't get bull 3 to work at all

**Comment by Climax777** [comment]
I've removed the cancellation config in the breaking part and configured bluebird early on in my own code. Still no job running happens. 2 worked perfectly with the same code.

**Comment by Climax777** [comment]
Okay the issue was that the example showin in the README.md file doesn't work:
```
  paymentsQueue.process(function(job){
    // Check payments
  });

  // Repeat payment job once every day at 3:15 (am)
  paymentsQueue.add(paymentsData, {repeat: '15 3 * * *'});
```

It has to look like this:
```
  paymentsQueue.process(function(job){
    // Check payments
  });

  // Repeat payment job once every day at 3:15 (am)
  paymentsQueue.add(paymentsData, {repeat: {cron: '15 3 * * *'}}); // *********
```

So that is probably a different issue. This issue is still about the problem with promise...

**Comment by manast** [comment]
Ok, thanks for the report. You are right, the README is wrong I will update it ASAP. Regarding the cancellation, it is a bit unfortunate that bluebird config is global, basically it means that if your code requires bull later than other code that uses bluebird, the error you reported will arise. I will try to find a solution. Worst case we can remove the cancel call, since it is just for cleaner code, it is not really needed.

**Comment by Climax777** [comment]
Thanks @manast . I also want to confirm, when creating repeat jobs, should I specify my own unique job id? I want to prevent rerunning the code somewhere else will create duplicate repeating jobs.

**Comment by manast** [comment]
@Climax777 no, the repeat functionality takes care of avoiding duplicate jobs. The id is generated from the cron pattern and the next time the job should be processed.

**Comment by Climax777** [comment]
@manast it doesn't seem to be the case. If I restart my worker, which also calls the same add `checkAllNoComms.add({}, {repeat: {cron: '* * * * *'}});` I get the job more than once per minute:
```
checkAllNoComms 2017-05-26T08:21:00.453Z
checkAllNoComms 2017-05-26T08:21:23.548Z
checkAllNoComms 2017-05-26T08:21:41.247Z
checkAllNoComms 2017-05-26T08:22:00.480Z
checkAllNoComms 2017-05-26T08:22:23.596Z
checkAllNoComms 2017-05-26T08:22:41.293Z
```

Though when adding my own jobId to that add `checkAllNoComms.add({}, {jobId: 'checkAllNoCommsRepeater', repeat: {cron: '* * * * *'}});` I only get one per minute, regardless of how many times I restart the worker:
```
checkAllNoComms 2017-05-26T08:31:09.708Z
checkAllNoComms 2017-05-26T08:32:09.723Z
checkAllNoComms 2017-05-26T08:33:09.760Z
```

**Comment by manast** [comment]
weird, I will check this in more depth
