### ISSUE TITLE
Error: cannot enable cancellation after promises are in use

### ISSUE THREAD

**Issue by binarymee** [OptimalBits/bull#547]
Hello,

I am using bluebird in my hapi.js project. I am getting `Error: cannot enable cancellation after promises are in use` when I try to use bull in my application. 

```
/Users/binarymee/sample-app/node_modules/bluebird/js/release/debuggability.js:269
            throw new Error(
            ^

Error: cannot enable cancellation after promises are in use
    at Function.Promise.config (/Users/binarymee/sample-app/node_modules/bluebird/js/release/debuggability.js:269:19)
    at Object.<anonymous> (/Users/binarymee/sample-app/node_modules/bull/lib/queue.js:22:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/binarymee/sample-app/server/workers/sample.js:1:75)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/binarymee/sample-app/server/controllers/billing.js:6:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

When I commented out the cancellation configuration for Promise in [queue.js](https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L22-L24), I was able to get rid of that error.,
```
Promise.config({
  cancellation: true
});
```

**Comment by manast** [comment]
yes, it was reported earlier today, I will make a fix for this and release a new version.
https://github.com/OptimalBits/bull/issues/546#issuecomment-304224692
