### ISSUE TITLE
Broken UI projects with Bull v3.0.0

### ISSUE THREAD

**Issue by binarymee** [OptimalBits/bull#562]
All UI Projects listed to monitor Bull is broken on v3.0.0. Because most of them relies on [Matador](https://github.com/ShaneK/Matador) and Matador is broken.

A sample error,

```
TypeError: completedJobs.keys[explodedKeys[1]].indexOf is not a function
    at /app/node_modules/bull-ui/models/redis.js:229:112
    at _fulfilled (/app/node_modules/bull-ui/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/app/node_modules/bull-ui/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/app/node_modules/bull-ui/node_modules/q/q.js:756:13)
    at /app/node_modules/bull-ui/node_modules/q/q.js:564:44
    at flush (/app/node_modules/bull-ui/node_modules/q/q.js:110:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Mostly due to change in the key types managed by Bull in Redis. 

I know it is irrelevant to post Matador's error here, since it is not managed by Bull. But, I thought of creating an issue here, since there are officially mentioned UI projects in ReadME.

**Comment by manast** [comment]
The README has been updated to reflect this fact.

**Comment by Prozer1** [comment]
Hello, I still have this issue and cannot find any solutions on the README or anywhere else,
Can you develop a little bit the answer ? 

(The error is exactly the same)

Thanks you very much
