### ISSUE TITLE
Job#remove issue

### ISSUE THREAD

**Issue by nanom1t** [OptimalBits/bull#575]
Hi, 

I'm using Bull in my Node.js application and I'm trying to use repeating jobs. So, I created new job in queue, which will run every 5 seconds: 
```
queue.add({a: 1, b: 2}, {repeat: { cron: '*/5 * * * * *' }});
```
I have a worker for this repeating job and I want to remove the job from Redis after completion:
```
queue.process(function (job, done) {
    ...
    job.remove().then(function () {
        done();
    });
});
```
However, I get next error:
```
Unhandled rejection Error: Could not remove job 1
    at Error (native)
    at /vagrant/node_modules/bull/lib/job.js:310:13
    at tryCatcher (/vagrant/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/vagrant/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/vagrant/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/vagrant/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/vagrant/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/vagrant/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/vagrant/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/vagrant/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```
I just want to remove completed jobs like "bull:vip:repeat:__default__:1497444535000" and continue repeat jobs.

How to resolve this issue?

Thanks

**Comment by manast** [comment]
The error is because you are trying to remove a locked job. A job is locked until process is done with it. The proper way to remove jobs is to use the ```removeOnComplete``` and ```removeOnFail``` options: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd

**Comment by nanom1t** [comment]
As I've understood from here https://github.com/OptimalBits/bull/blob/master/REFERENCE.md a particular job has these methods:
- Job#remove
- Job#retry
- Job#discard
- Job#promote
Also the job has a few statuses: completed, wait, active, delayed, and failed.

How can I change job status or fail it manually? For example, if something is wrong on my side I don't want to mark job as completed using method done(). I want to fail job and set some reason why that happened.
```
queue.process(function (job, done) {
    ...
    fail('something wrong with input data');
});
```

**Comment by manast** [comment]
In that particular case just throw an error and the job will fail with the error message as reason.
```js
queue.process(function (job, done) {
    ...
    throw new Error('something wrong with input data');
});
```
