### ISSUE TITLE
Cannot remove a stuck job.

### ISSUE THREAD

**Issue by bhanuc** [OptimalBits/bull#626]
Err stack: 
```
{
  "error": "bull error",
  "details": "Error: Could not remove job 12\n    at /exp/csv_exporter/app/node_modules/bull/lib/job.js:312:13\n    at tryCatcher (/exp/csv_exporter/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/exp/csv_exporter/app/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/exp/csv_exporter/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/exp/csv_exporter/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/exp/csv_exporter/app/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/exp/csv_exporter/app/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/exp/csv_exporter/app/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/exp/csv_exporter/app/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:800:20)\n    at tryOnImmediate (timers.js:762:5)\n    at processImmediate [as _immediateCallback] (timers.js:733:5)"
}
```
I am using bulls-ui to delete the task.

**Comment by manast** [comment]
Please report the issue in the bull-ui repo.
