### ISSUE TITLE
Missing lock for job

### ISSUE THREAD

**Issue by ritter** [OptimalBits/bull#647]
Having some issues with 3.0.0-rc.5 at the moment, might only be with repeat jobs.

> Error: Missing lock for job repeat:myjobname::1502484000000 finished
    at Object.finishedErrors (./node_modules/bull/lib/scripts.js:141:23)
    at ./node_modules/bull/lib/scripts.js:133:23
    at tryCatcher (./node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (./node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (./node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (./node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (./node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (./node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (./node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (./node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Any suggestions?  I've flushed redis db and re-added my repeat jobs and I get the same thing.

**Comment by manast** [comment]
No idea what can be cause this behaviour yet.

**Comment by npahucki** [comment]
I've seen the same with non repeat jobs.

**Comment by ritter** [comment]
Closing, not happening with 3.0.0-rc.6 that I can see.
