### ISSUE TITLE
Error running script - 3.3.0 - inside docker/Ubuntu

### ISSUE THREAD

**Issue by barczaG** [OptimalBits/bull#720]
I have the following error if running the tests inside a docker container - Ubuntu linux: 
Everything works fine on 3.2.0
Can provide minimum test case if needed.
```
{ ReplyError: ERR Error running script (call to f_bf0edc581619a27a39587a4a5acab6d636c5d607): @user_script:38: @user_script: 38: Lua redis() command arguments must be strings or integers
    at JavascriptRedisParser.returnError (/app/node_modules/ioredis/lib/redis/parser.js:24:25)
    at JavascriptRedisParser.execute (/app/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/app/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
  name: 'ReplyError',
  message: 'ERR Error running script (call to f_bf0edc581619a27a39587a4a5acab6d636c5d607): @user_script:38: @user_script: 38: Lua redis() command arguments must be strings or integers ',
  command:
   { name: 'evalsha',
     args:
      [ 'bf0edc581619a27a39587a4a5acab6d636c5d607',
        '8',
        'bull:cr-game-engine-service:wait',
        'bull:cr-game-engine-service:active',
        'bull:cr-game-engine-service:priority',
        'bull:cr-game-engine-service:active@14eadcef-d12a-449b-b794-4aa32d7e0d0d',
        'bull:cr-game-engine-service:stalled',
        'bull:cr-game-engine-service:limiter',
        'bull:cr-game-engine-service:delayed',
        'bull:cr-game-engine-service:',
        '14eadcef-d12a-449b-b794-4aa32d7e0d0d',
        '30000',
        '1507640259840',
        '' ] } }
{ ReplyError: ERR Error running script (call to f_bf0edc581619a27a39587a4a5acab6d636c5d607): @user_script:38: @user_script: 38: Lua redis() command arguments must be strings or integers
    at JavascriptRedisParser.returnError (/app/node_modules/ioredis/lib/redis/parser.js:24:25)
    at JavascriptRedisParser.execute (/app/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/app/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
  name: 'ReplyError',
  message: 'ERR Error running script (call to f_bf0edc581619a27a39587a4a5acab6d636c5d607): @user_script:38: @user_script: 38: Lua redis() command arguments must be strings or integers ',
  command:
   { name: 'evalsha',
     args:
      [ 'bf0edc581619a27a39587a4a5acab6d636c5d607',
        '8',
        'bull:cr-game-engine-service:wait',
        'bull:cr-game-engine-service:active',
        'bull:cr-game-engine-service:priority',
        'bull:cr-game-engine-service:active@14eadcef-d12a-449b-b794-4aa32d7e0d0d',
        'bull:cr-game-engine-service:stalled',
        'bull:cr-game-engine-service:limiter',
        'bull:cr-game-engine-service:delayed',
        'bull:cr-game-engine-service:',
        '14eadcef-d12a-449b-b794-4aa32d7e0d0d',
        '30000',
        '1507640259841',
        '' ] } }
{ ReplyError: ERR Error running script (call to f_bf0edc581619a27a39587a4a5acab6d636c5d607): @user_script:38: @user_script: 38: Lua redis() command arguments must be strings or integers
    at JavascriptRedisParser.returnError (/app/node_modules/ioredis/lib/redis/parser.js:24:25)
    at JavascriptRedisParser.execute (/app/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/app/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
  name: 'ReplyError',
  message: 'ERR Error running script (call to f_bf0edc581619a27a39587a4a5acab6d636c5d607): @user_script:38: @user_script: 38: Lua redis() command arguments must be strings or integers ',
  command:
   { name: 'evalsha',
     args:
      [ 'bf0edc581619a27a39587a4a5acab6d636c5d607',
        '8',
        'bull:cr-game-engine-service:wait',
        'bull:cr-game-engine-service:active',
        'bull:cr-game-engine-service:priority',
```

**Comment by manast** [comment]
Sorry for the late response, do you have more info regarding this issue?

**Comment by manast** [comment]
I will close this one for lack of feedback.
