### ISSUE TITLE
Cron repeatable jobs seem to fail with ? character

### ISSUE THREAD

**Issue by githubandrewd** [OptimalBits/bull#814]
Bull version "3.3.7"
I was trying to put a job that would repeat itself every minute

        BroadcastWorker.add({
          type: 'check_published_broadcasts',
        }, {
          repeat: {
            cron: '0 0/1 * ? * *', // Every 1 minute
          }
        })

but executing those lines fails with this:

Unhandled rejection Error: Invalid characters, got value: ?
    at Function._parseField (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/cron-parser/lib/expression.js:156:11)
    at parse (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/cron-parser/lib/expression.js:711:36)
    at Function.parse (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/cron-parser/lib/expression.js:722:10)
    at Function.parseExpression (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/cron-parser/lib/parser.js:39:25)
    at getNextMillis (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bull/lib/repeatable.js:110:27)
    at Queue.nextRepeatableJob (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bull/lib/repeatable.js:25:22)
    at /Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bull/lib/queue.js:617:20
    at tryCatcher (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/anhdao/Documents/projects/reactjs-projects/chatfunnelscom/cfc-backend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)

**Comment by manast** [comment]
use this expression instead (? does not seem to be supported by cron-parse): ```* * * * *```

**Comment by githubandrewd** [comment]
Thanks. This works.
