### ISSUE TITLE
TypeError when retrying jobs.

### ISSUE THREAD

**Issue by mscharley** [OptimalBits/bull#870]
## Description

We're getting an error trying to retry queue items. This is a manual process for us, after we fix the bug that led to the item failing in the first place then we run this task which retries them all.

The error we're receiving is as follows:

```
TypeError: queue.client.reprocessJob is not a function
    at Object.reprocessJob (/usr/src/app/node_modules/bull/lib/scripts.js:393:25)
    at Job.retry (/usr/src/app/node_modules/bull/lib/job.js:265:18)
    at Object.<anonymous> (/usr/src/app/src/lambda/ResetQueue.ts:29:13)
    at next (native)
    at fulfilled (/usr/src/app/src/lambda/ResetQueue.ts:4:58)
```

## Test code to reproduce

```typescript
const jobs = await queue.getFailed();
logger.info(`Resetting ${jobs.length} failed jobs in ${queueName}.`);
for (const job of jobs) {
  // this is the failing line.
  job.retry();
}
```

## Bull version

Affects Bull 3.3.9, is fine in 3.3.8.

## Additional information

For now, we're rolling back to 3.3.8. If you need any more info then please ask.

**Comment by manast** [comment]
Ok, it seems that reprocessJob has been refactored away. Sadly no unit test was present testing that function.

**Comment by a-samad** [comment]
getting same error when retrying on pending jobs

**Comment by manast** [comment]
Currently a simple test that tries to reproduce this issue has been added, but it is passing, can you please verify if this issue still exists in 3.4.1 ? if so, can you write another test case that reproduces it?

**Comment by artem-a** [comment]
Hi, yes this issue is still in 3.4.1

### Error
```
TypeError: queue.client.reprocessJob is not a function
     at Object.reprocessJob (/opt/jobs-processor/node_modules/bull/lib/scripts.js:465:25)
     at Job.retry (/opt/jobs-processor/node_modules/bull/lib/job.js:294:18)
     at queue.getFailed.then (/opt/jobs-processor/commands/JobRetry.js:31:19)
```

### Code
```javascript
    const queue = Queue.create(name)
    const count = await queue.getFailedCount()
    const jobs = await queue.getFailed()

    debug(name)
    debug(`failed count ${count}`)
    debug('start retries')

    for (const j of jobs) {
      await j.retry()
    }

    queue.close()
    debug('finish retries')
```

**Comment by manast** [comment]
@artem-a  we have a similar test case that passes without problems: https://github.com/OptimalBits/bull/blob/master/test/test_job.js#L217
Please provide a code that reproduces the issue that I can run deterministically to verify the issue.Note, the code that you provided does not run by its own.

**Comment by artem-a** [comment]
@manast so,here's the code I'm trying to execute through the command **node test.js**

**test.js**

```javascript
'use strict'

require('dotenv').config()

const Queue = require('bull')

const {
  BLOCKS_QUEUE,
  REDIS_HOST,
  REDIS_PORT
} = process.env

const blocksQueue = new Queue(BLOCKS_QUEUE,
  { redis: { host: REDIS_HOST, port: REDIS_PORT }})

blocksQueue.getFailedCount().then(console.log)

blocksQueue.getFailed().then(async jobs => {
  for (const j of jobs) {
    try {
      await j.retry()
    } catch (err) {
      console.log(err)
    }
  }
})
```
**env variables**

```
BLOCKS_QUEUE=blocks-queue
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
```
**errors**
```
TypeError: queue.client.reprocessJob is not a function
    at Object.reprocessJob (/opt/jobs-processor/node_modules/bull/lib/scripts.js:465:25)
    at Job.retry (/opt/jobs-processor/node_modules/bull/lib/job.js:294:18)
    at blocksQueue.getFailed.then (/opt/jobs-processor/test.js:21:15)
```
but I noticed if I run this code from the node REPL, it works without errors
```
> require('dotenv').config()
{ parsed: 
   { DEBUG: 'jobs:*',
     BLOCKS_QUEUE: 'blocks-queue',
     REDIS_HOST: '127.0.0.1',
     REDIS_PORT: '6379' } }
> 
> const Queue = require('bull')
undefined
> 
> const {
...   BLOCKS_QUEUE,
...   REDIS_HOST,
...   REDIS_PORT
... } = process.env
undefined
> 
> const blocksQueue = new Queue(BLOCKS_QUEUE, { redis: { host: REDIS_HOST, port: REDIS_PORT }})
undefined
> 
> blocksQueue.getFailedCount().then(console.log)
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> 828
> 
> blocksQueue.getFailed().then(async jobs => {
...   for (const j of jobs) {
.....     try {
.......       await j.retry()
.......     } catch (err) {
.......       console.log(err)
.......     }
.....   }
... })
Promise {
  <pending>,
  domain: 
   Domain {
     domain: null,
     _events: 
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> 
> blocksQueue.getFailedCount().then(console.log)
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> 0
```

**Comment by artem-a** [comment]
problem in this line [465](https://github.com/OptimalBits/bull/blob/master/lib/scripts.js#L465l)

when we run **node test.js**, `queue.client.reprocessJob` is undefined
when we run code from node REPL, `queue.client.reprocessJob` is [Function]
