### ISSUE TITLE
Error: Error initializing Lua scripts & ECONNREFUSED 127.0.0.1:6379 on heroku

### ISSUE THREAD

**Issue by milesalex** [OptimalBits/bull#928]
## Description

I'm having trouble getting the `client` / `subscriber` code working on heroku

I am getting this error:

```
2018-05-07T23:47:40.397285+00:00 app[reports.1]: info:  Error: Error initializing Lua scripts
2018-05-07T23:47:40.397289+00:00 app[reports.1]:     at /app/node_modules/bull/lib/queue.js:147:31
2018-05-07T23:47:40.397291+00:00 app[reports.1]:     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2018-05-07T23:47:40.397307+00:00 app[reports.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
2018-05-07T23:47:40.397313+00:00 app[reports.1]:     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
2018-05-07T23:47:40.397315+00:00 app[reports.1]:     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
2018-05-07T23:47:40.397316+00:00 app[reports.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:689:18)
2018-05-07T23:47:40.397318+00:00 app[reports.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
2018-05-07T23:47:40.397319+00:00 app[reports.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
2018-05-07T23:47:40.397321+00:00 app[reports.1]:     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
```

```
2018-05-07T23:47:40.402330+00:00 app[reports.1]: Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:6379
2018-05-07T23:47:40.402333+00:00 app[reports.1]:     at Object._errnoException (util.js:1022:11)
2018-05-07T23:47:40.402334+00:00 app[reports.1]:     at _exceptionWithHostPort (util.js:1044:20)
2018-05-07T23:47:40.402336+00:00 app[reports.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```

And I think it's referring to this code:

https://github.com/OptimalBits/bull/blob/master/lib/queue.js?utf8=%E2%9C%93#L130-L152

## Test code to reproduce

```js
import Redis from 'ioredis'
import Queue from 'bull'

const { REDIS_URL } = process.env

const client = new Redis(REDIS_URL)
const subscriber = new Redis(REDIS_URL)

function createQueue (name) {
  const queue = new Queue(name, {
    redis: {
      opts: {
        createClient: type => {
          switch (type) {
            case 'client':
              return client
            case 'subscriber':
              return subscriber
            default:
              return new Redis()
          }
        },
      },
    },
  })
}
```

## Bull version

3.4.1

**Comment by manast** [comment]
It seems like you have a wrong configuration for your redis instance:
```
Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:6379
```

**Comment by milesalex** [comment]
I’m definitely pulling in the correct url from heroku. I’ll try to verify again.

**Comment by manast** [comment]
In your "createQueue" code you are calling: 
```
new Redis()
```
which by default will try to connect to localhost.

**Comment by milesalex** [comment]
Had too many wrapping objects. This code works. False alarm!

```js
function createQueue(name) {
  const queue = new Queue(name, {
    createClient: type => {
      switch (type) {
        case "client":
          return client;
        case "subscriber":
          return subscriber;
        default:
          return new Redis();
      }
    }
  });
}
```
