### ISSUE TITLE
TypeError: job.queue.client.isFinished is not a function

### ISSUE THREAD

**Issue by hbakhtiyor** [OptimalBits/bull#949]
## Description
getting error on `await job.finished()`

## Test code to reproduce
```js
async function queueProcess(job) {
  return await demoFunc(
    job.data.url,
    async (data) => {
      await job.progress({data});
    }
  );
}

var Queue = require('bull');

const queue = new Queue('demo');
queue.process(queueProcess);

let job;
job = await queue.getJob(uuid);
if (!job) {
  job = await queue.add({data}, {jobId: uuid, removeOnComplete: true, removeOnFail: true});
}

queue.on('progress', async (_job, {data}) => {
  if(_job.id === job.id) {
    // todo something
  }
});

const result = await job.finished();

```
## Bull version
3.4.2

**Comment by manast** [comment]
the test code does not work, it is missing things like demoFunc, uuid, etc.

**Comment by hbakhtiyor** [comment]
instead use dummy functions, variables, getting error when using already existing job `job = await queue.getJob(uuid);`

**Comment by hbakhtiyor** [comment]
the error

```
TypeError: job.queue.client.isFinished is not a function
    at Object.isFinished (/demo/node_modules/bull/lib/scripts.js:228:29)
    at Job.finished (/demo/node_modules/bull/lib/job.js:383:18)
    at app.get (/demo/demo.js:81:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```
here's some working sample
tested in node 10.1.0, ubuntu 18.04
using docker base [redis](https://hub.docker.com/_/redis/) (4.0.9) and run without any additional configuration `docker run -d -p 6379:6379 redis`

```js
const express = require('express')
const Queue = require('bull');
const uuidV5 = require('uuid/v5');

const app = express();

// pre-defined uuid json namespace
const UUID_JSON = '18e8eebd-77b5-4f97-acac-2c0e2cca482b';


async function sleep(delay) {
  return new Promise((ok, fail) => {
    setTimeout(ok, delay * 1000);
  });
}

async function addFunc(a, b, cb) {
  const add = a + b;
  if (cb) {
    await sleep(1);
    await cb('processing #1');
    await sleep(2);
    await cb('processing #2');
    await sleep(2);
    await cb(add);
  }
  return add;
}

async function queueAddProcess(job) {
  const result = await addFunc(
    job.data.a,
    job.data.b,
    job.data.stream ?
    async (data) => {
      await job.progress({data});
    } : null
  );

  let final;
  if (result % 2 === 0) {
    final = result + 2;
  } else {
    final = result + 1;
  }

  return Promise.resolve(final);
}

app.get('/add/:a/:b/:stream?', async (req, res) => {
  console.log('request params', req.params);
  const a = parseInt(req.params.a);
  const b = parseInt(req.params.b);
  const stream = req.params.stream === 'true';

  if (stream) {
    console.log('using streamming');
  }
  const queue = new Queue('add');
  queue.process(queueAddProcess);

  const uuid = uuidV5(JSON.stringify({a, b}), UUID_JSON);
  let job;
  job = await queue.getJob(uuid);
  if (!job) {
    job = await queue.add({a, b, stream}, {jobId: uuid, removeOnComplete: true, removeOnFail: true});
    console.log('added job');
  }

  queue.on('progress', async (_job, {data}) => {
    if(_job.id === job.id) {
      // progressing data
      // simulating delay
      await sleep(3);
      console.log(data);
      res.write(data);
    }
  });

  console.log('processing');
  const result = await job.finished();
  console.log('finished processing');
  if (stream) {
    res.end();
  } else {
    res.send(result.toString());
    console.log('sent request');
  }
});

app.listen(3000, () => console.log('Example app listening on port 3000!'));
```

* if we open http://localhost:3000/add/8/10/true, and open again while processing, we get the error

**Comment by ryan-esty** [comment]
Not sure if anyone is watching this bug or not but I'm getting something similar on ubuntu 16.04 bull 3.7.0 node v8.15.0. I can't upgrade right now but if people are still having issues I'd like to add more information to the bug. I'm using a call back method of adding stuff to the queue not promises. Everything seems to work but when I call the done function I get this error:
 TypeError: "callback" argument must be a function. I believe this is similar to this bug but if I don't get a response I'll open a new bug and reference this one.

My function passes the test of this instanceof Function but does not pass the test of === 'function'. I believe deep in the library somewhere it is using the next-tick and it only has the later check for a function. We are using the => operator to do the call back, which I'm not sure matters.
