### ISSUE TITLE
Typings - Waiting / Wait JobStatus

### ISSUE THREAD

**Issue by RDeluxe** [OptimalBits/bull#965]
## Description

It seems that the Typescript typings describe the JobStatus this way : 

`type JobStatus = 'completed' | 'waiting' | 'active' | 'delayed' | 'failed';`

However, trying to clean a queue using `waiting` will resolve in an error

```
 Unhandled rejection Error: Cannot clean unknown queue type waiting
[1] sonly-api   |     at Queue.clean (/home/node/app/node_modules/bull/lib/queue.js:1142:27)
[1] sonly-api   |     at BullCronService.JobQueue.clean.then.then (/home/node/app/src/modules/bull/bull.cron.service.ts:31:33)
[1] sonly-api   |     at runCallback (timers.js:696:18)
[1] sonly-api   |     at tryOnImmediate (timers.js:667:5)
[1] sonly-api   |     at processImmediate (timers.js:649:5)
[1] sonly-api   |     at process.topLevelDomainCallback (domain.js:121:23)
[1] sonly-api   | From previous event:
[1] sonly-api   |     at new BullCronService (/home/node/app/src/modules/bull/bull.cron.service.ts:31:8)
[1] sonly-api   |     at Injector.<anonymous> (/home/node/app/node_modules/@nestjs/core/injector/injector.js:81:88)
[1] sonly-api   |     at Generator.next (<anonymous>)
[1] sonly-api   |     at /home/node/app/node_modules/@nestjs/core/injector/injector.js:7:71
[1] sonly-api   |     at new Promise (<anonymous>)
[1] sonly-api   |     at __awaiter (/home/node/app/node_modules/@nestjs/core/injector/injector.js:3:12)
[1] sonly-api   |     at resolveConstructorParams (/home/node/app/node_modules/@nestjs/core/injector/injector.js:79:98)
[1] sonly-api   |     at Injector.<anonymous> (/home/node/app/node_modules/@nestjs/core/injector/injector.js:105:34)
[1] sonly-api   |     at Generator.next (<anonymous>)
[1] sonly-api   |     at fulfilled (/home/node/app/node_modules/@nestjs/core/injector/injector.js:4:58)
[1] sonly-api   |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Minimal, Working Test code to reproduce the issue.

```ts
import * as Bull from 'bull';
import { Queue } from 'bull';

export class BullCronService {
  public JobQueue: Queue;
  private JobDuration: number = 30;

  public constructor(private readonly jobService: JobService) {
    this.JobQueue = new Bull('JobQueue', {
      redis: { port: parseInt(config.redis.port, 10), host: config.redis.host },
    });

    this.JobQueue.on('failed', (job, err) => {
      // tslint:disable-next-line
      console.error(err);
    });

    this.JobQueue.on('completed', (job, result) => {
      // tslint:disable-next-line
      console.log(result);
    });

    this.JobQueue.clean(0, 'active')
      .then(() => this.JobQueue.clean(0, 'delayed'))
      .then(() => this.JobQueue.clean(0, 'waiting'))
      .then(() => {
        this.JobQueue.process('DisableJobs', this.DisableJobTask.bind(this));
        this.JobQueue.add('DisableJobs', {}, { repeat: { cron: '* */5 * * * *' } });
      });
  }

  private async DisableJobTask(job: Bull.Job) {
    try {
     // Stuff
     return Promise.resolve();
    } catch (error) {
      return Promise.reject(new Error(error));
    }
  }
}
```

## Bull version
bull@^3.4.2

**Comment by manast** [comment]
A PR should be addressed here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bull

(Unfortunately I do not maintain those typings ...)

**Comment by chenop** [comment]
So how do I clean the waiting jobs?

**Comment by WaleedAshraf** [comment]
Use the status "wait" @chenop 

As per here: https://github.com/OptimalBits/bull/blob/f9081dd01f24dabd96f4d754c821779b1bbaaa07/lib/queue.js#L1259
